/**
 * French translation of the changing-line Now readings. Mirrors NOW_LINES in
 * now-lines.ts (6 per hexagram, bottom→top); falls back to English when missing.
 */
export const NOW_LINES_FR: Record<number, string[]> = {
  1: [
    "Le potentiel est réel, mais ce n'est pas le moment. Restez sous terre, continuez à bâtir en privé, et n'agissez pas encore.",
    "On commence à vous remarquer, et le travail prend vraiment forme. C'est le moment de trouver un mentor, quelqu'un d'une vraie stature.",
    "Effort acharné toute la journée, encore en alerte la nuit — forte pression et risque réel. Gardez votre intégrité à travers tout ça et vous en sortez net.",
    "Vous êtes à la croisée des chemins : sauter ou patienter. L'un comme l'autre va, si le choix est honnête et vraiment le vôtre, sans peur ni esbroufe.",
    "Vous maîtrisez pleinement vos forces et vous êtes visible au sommet. Servez-vous bien de cette portée : soutenez les vrais talents et laissez votre influence agir.",
    "Vous êtes allé trop loin, et il n'y a plus rien au-dessus. L'orgueil au sommet prépare la chute — reculez avant qu'elle ne vous emporte.",
  ],
  2: [
    "Le premier givre annonce la glace à venir. Repérez dès maintenant le petit signe précoce, car les petites choses durcissent en grandes conditions si on les ignore.",
    "Quand vous êtes ancré et d'aplomb avec le réel, pas besoin de manœuvrer. Agissez droit depuis cette base et les choses avancent sans forcer.",
    "Faites le travail sans réclamer le mérite. Restez discret, finissez ce qu'on vous a confié, et laissez la reconnaissance vous trouver plus tard.",
    "Dans un moment tendu, sous les regards, ne dites rien et ne révélez rien. Gardez le sac fermé — ni éloge ni blâme, gardez vos pensées pour vous.",
    "Une vraie valeur portée discrètement, jamais étalée, c'est ce qui rapporte le plus. Restez centré, restez modeste, et laissez le mérite se montrer de lui-même.",
    "Quand vous affrontez de front une force plus puissante comme si vous étiez égaux, vous y laissez tous les deux des plumes. N'allez pas dans une bataille dont personne ne sort indemne.",
  ],
  3: [
    "Le démarrage est bloqué et forcer n'arrangera rien. Faites une pause, alignez vos alliés et vos appuis, et préparez le terrain pour le vrai départ.",
    "Les obstacles s'empilent et l'affaire ne se conclut pas encore. Ne forcez pas l'engagement maintenant — attendez que les conditions mûrissent vraiment, même si c'est lent.",
    "Poursuivre la cible sans guide ne fait que vous égarer plus profond. Lisez les signes, lâchez celle-ci ; forcer ne vous achète que l'humiliation.",
    "Vous êtes à l'arrêt, mais c'est le moment de tendre la main. Allez chercher le bon partenaire ouvertement — c'est ce qui ouvre la voie.",
    "Vous ne pouvez pas livrer la grande chose : les circonstances ne le permettent pas. Donnez à petite échelle, restez stable ; trop en faire maintenant se retourne contre vous.",
    "Tout s'est effondré et rien ne tient plus. Cessez de traîner le poids mort, lâchez prise — le chagrin est réel, mais le relâcher est la seule issue.",
  ],
  4: [
    "Posez tôt une limite claire pour briser la mauvaise habitude, puis relâchez. Punir au-delà de la leçon ne fait que durcir la résistance.",
    "Soyez patient et généreux avec les inexpérimentés. Accueillez-les comme les vôtres, enseignez sans mépris, et toute l'équipe se stabilise.",
    "Ne vous liez pas à quelqu'un qui perd la tête et ses appuis à la première chose qui brille. Vous n'en tirerez rien.",
    "Un esprit qui se ferme à toute correction se fige dans son erreur. Sourd à l'enseignement, il ne récolte que sa propre humiliation.",
    "Admettre qu'on ne sait pas, c'est l'ouverture, pas la faiblesse. Cette posture honnête du débutant, c'est précisément ce qui attire l'aide vers vous.",
    "Corrigez l'erreur, n'en faites pas une guerre. Écartez le mal, arrêtez-vous avant la cruauté — la surcorrection devient une faute à son tour.",
  ],
  5: [
    "Vous êtes loin du danger, alors ne fabriquez pas d'urgence. Tenez-vous-en à votre routine et à ce qui dure ; restez simplement stable et net.",
    "Les ennuis se rapprochent et les rumeurs commencent. Attendez-vous à des frictions mineures et à des critiques mesquines — encaissez, ça finit quand même bien.",
    "Vous vous êtes trop approché et vous voilà englué dans la boue, à inviter les ennuis. Ralentissez, restez vigilant, et vous limitez les dégâts.",
    "Vous êtes dans la fosse maintenant, dépassé par les événements. Ne vous débattez pas — restez calme et souple, et on vous en sortira.",
    "Prenez la pause au milieu de l'effort : mangez, reposez-vous, récupérez. Tenez bon pendant le répit et vous aurez la force pour le reste.",
    "Juste quand tout semble au pire, une aide inattendue surgit. Traitez avec respect ceux que vous n'aviez pas appelés, et le mauvais tournant devient bon.",
  ],
  6: [
    "Lâchez le conflit tôt. Il y aura un peu de ragots, mais laissez-le retomber maintenant et l'affaire se dissout au lieu de s'envenimer.",
    "Vous ne pouvez pas gagner cette bataille, alors reculez et désengagez-vous en silence. Cédez à temps et ceux qui dépendent de vous ne subissent aucun dommage.",
    "Appuyez-vous sur la solide réputation que vous avez déjà bâtie et tenez simplement bon malgré le risque. Si vous servez la cause d'un autre, n'en revendiquez rien.",
    "Vous ne pouvez pas gagner l'affrontement, alors arrêtez. Acceptez la réalité telle qu'elle est, changez d'avis, et retrouvez vos appuis en faisant ce qui est juste.",
    "Portez l'affaire devant un arbitre juste et impartial. Quand la bonne personne pèse le dossier sur le fond, tout se règle proprement — le meilleur dénouement.",
    "Même si vous gagnez et raflez le prix, vous le reperdrez encore et encore. Une victoire arrachée par la force ne se garde pas ; la bataille n'en vaut pas la peine.",
  ],
  7: [
    "Lancez l'effort avec discipline et ordre dès le premier jour. Sans cette structure en amont, même une bonne cause s'effondre dans le chaos.",
    "Menez du milieu de vos gens, pas au-dessus d'eux. Tenez le centre, gagnez leur confiance, et le soutien d'en haut viendra le confirmer.",
    "Ne laissez pas le commandement se diviser ou tomber aux mains des incapables — c'est ainsi que tout finit en désastre. Une direction unique, claire et compétente.",
    "Se replier et se regrouper n'est pas un échec. Savoir quand ne pas avancer est en soi le signe que vous savez vraiment commander.",
    "Saisissez l'occasion claire qui se présente — c'est de bon droit, aucun reproche. Mais mettez aux commandes votre personne la plus aguerrie, pas la novice.",
    "Une fois la victoire acquise, récompensez ceux qui l'ont méritée et bâtissez le nouvel ordre. Mais ne confiez pas le vrai pouvoir aux mauvaises personnes, sous peine de défaire le gain.",
  ],
  8: [
    "Ralliez-vous avec une sincérité véritable et vous restez net. Soyez honnêtement plein à ras bord, et la chance arrive d'une direction inattendue.",
    "Que l'alliance vienne de ce que vous êtes vraiment, pas du besoin. Les liens nés de votre propre nature tiennent sans vous coûter vous-même.",
    "Ne vous liez pas aux mauvaises personnes. La loyauté dépensée pour ceux qui ne la méritent pas ne mène nulle part et vous épuise en terrain stérile.",
    "Engagez-vous pour les gens de valeur ouvertement, au grand jour, sans réserve cachée. Soutenir les bonnes personnes sans détour, c'est ce qui vous porte en avant.",
    "Menez l'union sans contrainte : laissez aux gens une issue, comme la chasse qui rabat le gibier de trois côtés seulement. Personne n'est acculé, et ils restent de leur plein gré.",
    "Une alliance sans vrai meneur ni centre se défait. Si le début n'a jamais été bien posé, il n'y a pas de bonne fin à espérer.",
  ],
  9: [
    "Revenez sur votre propre chemin — aucune honte à cela. Le bon geste, c'est de retrouver ce qui est vraiment vôtre, pas de courir la route d'un autre.",
    "Quelqu'un devant vous fait les choses bien, et son exemple vous remet sur la voie. Suivez ce qui vous convient ; laissez le bon modèle corriger votre cap.",
    "Votre élan vient de se briser — les roues lâchent, les partenaires ne sont plus alignés. L'avancée ne tient pas ; quelque chose au cœur du projet résiste en silence, et le forcer le casse.",
    "Soyez droit et la peur s'écoule. Coincé dans une position serrée et risquée, vous avez gagné la confiance de ceux qui sont au-dessus de vous — et vous êtes tiré d'affaire.",
    "Vous êtes sincère, alors vous attachez les gens à vous. Rapprochez votre plus proche allié par l'honnêteté et partagez ce que vous avez au lieu de l'amasser.",
    "Enfin la récompense tombe et vous pouvez souffler — l'effort patient a porté. Mais n'allez pas au-delà ; insister maintenant, alors que la retenue a fait son œuvre, ne fait qu'appeler les ennuis.",
  ],
  10: [
    "Marchez sur votre chemin tout simple et avancez léger. Restez content du sobre et du sans-entrave, et vous progressez sans que personne vous le reproche.",
    "Tenez-vous à la route plane et tranquille. Celui qui reste discret et régulier, sans courir les projecteurs, garde son assise et s'en sort bien.",
    "Ne feignez pas une compétence que vous n'avez pas — le borgne qui joue le clairvoyant, le boiteux qui joue l'assuré se font mordre. Dépasser ses vraies capacités mène à la chute.",
    "Vous marchez sur la queue du tigre, mais vous le faites avec soin, pleinement conscient du danger. Mené avec autant de prudence, cela finit bien.",
    "Vous agissez avec décision et vous vous engagez à fond. Même quand vous avez raison, gardez vivant votre sens du risque — la fermeté ne doit pas basculer dans l'imprudence.",
    "Regardez en arrière tout le chemin parcouru et lisez ce qu'il vous dit. Quand la boucle complète se referme, c'est là qu'est la vraie chance.",
  ],
  11: [
    "Tirez une bonne personne et tout un réseau monte avec elle, racines entremêlées. Bougez maintenant — les bonnes personnes s'élèvent ensemble et amènent les leurs.",
    "Portez le brut et le novice, osez la traversée hardie, n'oubliez personne au loin, et ne formez aucune coterie. C'est ainsi qu'on tient le milieu en restant honnête.",
    "Toute ligne droite finit par pencher, tout départ finit par revenir — rien de bon ne dure éternellement. Restez stable dans le virage difficile, ne vous désolez pas, et profitez de ce qui vous est donné.",
    "Vous descendez sans étaler ce que vous avez, vous rapprochant des vôtres de bonne foi. Celui qui est en haut descend rejoindre le plus bas d'un cœur ouvert et sincère.",
    "Le puissant donne à l'humble une vraie part, et de cette union naît une chance profonde. Abaissez-vous pour élever un autre, et l'abondance suit.",
    "Le mur s'écroule dans le fossé. N'envoyez pas la force maintenant ; gardez vos décisions dans vos propres frontières. Même justifié, le regret vient — la bonne période a tourné.",
  ],
  12: [
    "Tirez-en un et tout le réseau suit — mais maintenant tenez bon et repliez-vous avec les vôtres. Gardez la foi en silence ; ce n'est pas le moment d'avancer.",
    "Ils serrent les dents et endurent ; les petits manœuvriers prospèrent là-dessus, mais vous acceptez l'arrêt et trouvez votre chemin. Ne vous laissez pas emporter par le courant commun.",
    "Il ravale sa honte en silence. Ceux qu'on a hissés au-dessus de leurs vraies capacités sont tourmentés en secret par un poste qu'ils ne peuvent porter.",
    "Vous agissez sur le plus haut mandat, et vous êtes sans reproche ; ceux qui partagent votre but partagent le gain. Le tournant commence à venir.",
    "Le blocage cède et les forts en sortent gagnants. Mais continuez à vous répéter « ça peut encore échouer, ça peut encore échouer », et arrimez votre sécurité à quelque chose de bien enraciné.",
    "L'arrêt se renverse : d'abord le blocage, puis le soulagement. Rien de coincé ne reste coincé — aucune situation ne tient en place pour toujours.",
  ],
  13: [
    "Communauté ouverte dès le seuil, en plein jour. Aucun reproche — un partenariat commencé sans secret ni favoritisme ne donne à personne matière à objecter.",
    "Une communauté qui n'inclut que votre propre clan. C'est un cran en dessous ; vous lier à un cercle restreint reste en deçà du terrain commun et ouvert.",
    "Il cache des armes dans les buissons et grimpe la colline pour guetter — et pendant trois ans ne peut faire un geste. La méfiance le tient armé mais paralysé.",
    "Vous escaladez le mur mais ne lancez pas l'assaut. Bien — vous reculez du combat et cédez à ce qui est juste.",
    "Après une lutte amère, ceux qui devaient être ensemble se retrouvent enfin — d'abord les larmes, puis le rire. Ce qui va vraiment ensemble ne peut être tenu séparé.",
    "Communauté en plein champ, au-delà des murs. Aucun regret, même si elle n'est pas encore pleinement réalisée — le but est sain là même où l'objectif n'est pas atteint.",
  ],
  14: [
    "Vous n'avez encore touché à rien de nuisible, donc vous êtes net. Gardez à l'esprit que cela pourrait devenir difficile et votre bonne position tient — au début, tout reste à l'épreuve et facile à garder clair.",
    "Un grand chariot pour la charge et une vraie destination où aller. Partez maintenant sans reproche — votre capacité est à la mesure d'un but qui en vaut la peine.",
    "Mettez vos ressources au service de quelque chose de plus grand que vous. La personne mesquine et avide en est incapable ; elle ne sait pas donner ce que l'abondance lui a remis.",
    "Restez dans votre mesure et ne singez pas l'étalage tape-à-l'œil du voisin. Aucun reproche — celui qui n'exhibe pas sa richesse échappe à l'envie de ceux d'en haut.",
    "Votre honnêteté rallie les gens et en attire autant en retour ; la chaleur tempérée d'une vraie dignité l'emporte. La sincérité portée sans arrogance attire tout le monde.",
    "Vous êtes porté par quelque chose de plus grand que vous. Quand vous tenez une vraie abondance en restant modeste et ancré, le soutien continue d'affluer — rien ne fait obstacle.",
  ],
  15: [
    "Modeste et encore modeste — cette humilité vous porte à travers la traversée difficile et cela va bien. Rester bas et sans prétention, c'est précisément ce qui vous fait franchir le danger.",
    "Une modestie assez méritée pour se voir, et chacun perçoit qu'elle est vraie. Tenez-y bon et cela va bien — une humilité qui sonne juste rallie les gens.",
    "Vous faites le gros du travail en restant modeste à son sujet, et vous menez l'ouvrage jusqu'au bout. Bien — un vrai mérite doublé d'humilité gagne une fidélité durable.",
    "Continuez à montrer de l'humilité dans votre manière même d'agir. Bougez dans vos limites sans les dépasser — ni vous rabougrir, ni franchir la ligne.",
    "Sans vous vanter de ce que vous avez, vous attirez les gens ; et maintenant il est juste de mettre une pression ferme sur ce qui ne cède pas. Même les mesures dures, faites avec humilité, sont au-dessus de tout reproche.",
    "Une humilité enfin prête à agir — vous pouvez maintenant bouger avec décision et remettre les choses en ordre dans votre propre domaine. Vous avez gagné la stature pour corriger ce qui est à votre portée.",
  ],
  16: [
    "Un enthousiasme bruyant et tape-à-l'œil, tout en façade, finit mal. Se vanter de ses relations et brûler son élan en vanité tarit la source.",
    "Solide comme le roc, et pas seulement pour un jour. Tenez bon et cela va bien — vous ne flattez personne au-dessus, ne méprisez personne en dessous, et lisez les premiers signes avant les autres.",
    "Un enthousiasme qui se contente de lever les yeux vers les puissants en attendant apporte le regret ; l'atermoiement aussi. Fixer ceux qui commandent au lieu d'agir vous fait perdre le moment à force d'hésiter.",
    "Vous êtes la source d'où tout découle, alors de grandes choses sont possibles. Ne vous remettez pas en question — les gens se rassemblent autour de vous comme une agrafe rassemble les brins épars.",
    "Maintenu à terre sans relâche, cerné par une pression constante venue d'en haut — mais pas fini. Le noyau en vous n'est pas étouffé ; vous persistez.",
    "Un enthousiasme devenu aveugle, perdu en lui-même — mais si vous vous ressaisissez avant qu'il soit trop tard et changez de cap, aucun reproche. Même l'illusion sur soi peut se racheter quand on fait demi-tour à temps.",
  ],
  17: [
    "Votre ancien repère a bougé, et ce qui vous tenait pointe désormais ailleurs. Sortez de votre bulle, allez vers de nouvelles personnes, et le travail portera ses fruits.",
    "Courir après l'option facile et confortable, c'est perdre celle qui compte vraiment. Vous ne pouvez pas avoir les deux — choisissez celle qui a du poids et laissez tomber le reste.",
    "Engagez-vous dans le travail sérieux et la distraction brillante tombe d'elle-même. Vous obtenez ce que vous êtes venu chercher, mais gardez votre cap clair pour ne pas vous laisser entraîner.",
    "Des gens commencent à vous suivre et votre influence grandit — c'est précisément là que les soupçons naissent. Restez honnête et transparent sur vos motivations, et rien n'accrochera.",
    "Vous êtes sincèrement engagé envers quelque chose de bon et vous le suivez sans vous remettre en question. Cette constance-là n'a besoin d'aucune justification.",
    "Votre engagement est total, verrouillé jusqu'au bout. Une dévotion aussi profonde est honorée au plus haut niveau — donnez-vous pleinement à ce qui le mérite.",
  ],
  18: [
    "Vous nettoyez un désordre dont vous avez hérité — le mauvais code d'un prédécesseur, la dette d'un parent, un système cassé. C'est un travail tendu, mais le mener à bout restaure le nom et finit bien.",
    "Vous réparez les dégâts laissés par quelqu'un envers qui vous ne pouvez pas être dur. Allez-y en douceur, ne forcez pas la correction ; ici, la main lourde ne fait qu'empirer les choses.",
    "Vous corrigez le problème hérité un peu trop énergiquement — léger regret pour l'excès, mais aucun vrai dommage.",
    "Tolérer la pourriture et lui trouver des excuses laisse la dégradation s'étendre. Continuez d'éviter le nettoyage et c'est vous qui en serez humilié.",
    "Vous entreprenez le nettoyage comme il faut et les gens le remarquent. Réparer ce qui était cassé vous vaut une vraie reconnaissance.",
    "Vous vous retirez de la routine commune pour poursuivre votre propre travail, plus élevé. En refusant de jouer le jeu habituel, vous cultivez quelque chose qui compte davantage — et cela en vaut la peine.",
  ],
  19: [
    "Vous avancez aux côtés d'autres qui partagent l'objectif, et la voie est ouverte. Tenez fermement à ce qui est juste et cela ira bien.",
    "Vous progressez ensemble vers quelque chose de bon et cela aboutit. Avancez sans vous remettre en question.",
    "Glisser sur le charme et la présomption ne vous mène nulle part. Mais si vous ressentez vraiment l'erreur et la corrigez, le reproche ne tiendra pas.",
    "Vous vous donnez pleinement au travail ou à la personne, sans rien retenir, et cela atterrit où il faut. Il n'y a aucune faute dans l'engagement total.",
    "Vous menez avec discernement — à travers les autres, sans accaparer chaque levier vous-même. Déléguer avec jugement est ce qui fait que cela marche.",
    "Vous approchez avec générosité et un cœur vaste et patient. La main large et sans hâte, vous ne pouvez pas vous tromper ici.",
  ],
  20: [
    "Vous n'effleurez que la surface et n'en voyez qu'une vue superficielle. Acceptable si peu dépend de vous, mais si vous portez une responsabilité, cette superficialité vous coûtera cher.",
    "Vous regardez l'ensemble par un trou de serrure, ne saisissant qu'une mince tranche. Cette vue limitée convient à un petit rôle, mais elle est gênante pour qui devrait voir plus large.",
    "Observez les résultats réels de vos propres choix — ce qui avance, ce qui se retourne contre vous — et laissez cela vous dire quand bouger et quand tenir. C'est ainsi qu'on lit le moment.",
    "Reculez et embrassez tout le paysage — la qualité et la portée de ce qui vous entoure. Voyez-le clairement et vous devenez quelqu'un qu'on a intérêt à inviter à la table.",
    "Regardez honnêtement votre propre conduite et l'effet que vous avez sur les autres. Jugez-vous à ce miroir et vous en sortez net.",
    "Regardez l'ensemble du tableau, les vies et les motifs au-delà de vous, pas seulement votre situation. Voyez aussi large et vous êtes sur un terrain solide.",
  ],
  21: [
    "Une petite faute vous fait prendre et corriger tôt, avant qu'elle ne grandisse. Mieux vaut être arrêté maintenant sur un détail que de la laisser s'aggraver — aucune honte à cela.",
    "Vous frappez fort et le tort est évident, alors vous mordez profond. La réprimande est cinglante, mais vu l'évidence de la faute, elle est justifiée.",
    "Vous vous attaquez à quelque chose de pourri et cela vous laisse un mauvais goût — vous vous brûlez un peu sur un problème vicié dès le départ. Légèrement humiliant, mais la tâche était vraiment dure, alors ce n'est pas votre faute.",
    "Vous tombez sur quelque chose de dur et d'emmêlé, mais à l'intérieur vous trouvez ce qui est solide et précieux. Restez lucide sur la difficulté, gardez-vous droit, persistez, et cela paie.",
    "Vous venez à bout du problème sec et tenace et vous y trouvez de l'or véritable. Gardez votre but, restez attentif au risque, et rien ne se retourne contre vous.",
    "Vous avez refusé chaque avertissement et vous voilà bloqué, incapable d'entendre ou de bouger. Devenir sourd à la correction, c'est ce qui fait s'abattre le désastre.",
  ],
  22: [
    "Vous préférez marcher selon vos propres termes que d'arriver porté par ce qui n'est pas vraiment à vous. En refusant un confort non mérité, vous restez sur votre route honnête.",
    "Votre éclat doit suivre la substance qu'il y a dessous, pas la précéder. Le style ne marche que lorsqu'il s'élève avec la chose réelle qu'il décore.",
    "Tout paraît étincelant, fluide, séduisant sans effort. Profitez-en, mais restez stable et ancré — gardez-le authentique dans la durée et la bonne fortune tient.",
    "Dépouillée d'ornement, la vérité nue arrive vite et nette. Ce qui ressemblait à une menace s'avère sincère ; une fois que vous voyez clair, le soupçon se dissout.",
    "Votre offrande est modeste, presque gênante de petitesse pour le contexte. Il y a une piqûre à donner si peu, mais la sincérité l'emporte sur l'apparence à la fin.",
    "Réduisez l'ornement au blanc le plus simple et il ne reste rien à reprocher. Quand la forme revient à la simplicité, elle est enfin devenue vraie.",
  ],
  23: [
    "La pourriture commence à la base, là où vous ne la voyez pas — les pieds du lit lâchent déjà. Le dommage sape vos fondations en silence ; c'est là que le trouble naît.",
    "La dégradation gagne maintenant la structure, et le soutien qui devrait tenir cède. Rester seul ici, sans alliés, est dangereux — n'y allez pas en solitaire.",
    "Vous rompez avec les gens emportés par le déclin, même si tout le monde autour de vous y est plongé. En choisissant ce qui est juste à contre-courant, vous restez net.",
    "Le dommage a atteint la peau — il vous touche directement maintenant, sans plus aucun tampon. La menace est juste sur vous et il n'y a aucun abri.",
    "Vous alignez tout le monde et les menez avec grâce vers la lumière, et tout tourne à votre avantage. Entraînez les gens en bon ordre et rien n'est gâché.",
    "Un fruit entier reste intact, gardant la graine du cycle suivant — survivez au dépouillement et le renouveau vient. Les gens ancrés perdurent tandis que les imprudents démolissent leur propre maison.",
  ],
  24: [
    "Vous vous rattrapez avant de vous être beaucoup enfoncé sur la mauvaise route et vous faites demi-tour. Pas besoin de vous flageller — corrigé tôt, le résultat est excellent.",
    "Vous revenez tranquillement et de bon gré, heureux de rentrer en bonne compagnie. Suivre ce qui est bon n'est pas une faiblesse ; cela va bien.",
    "Vous rechutez sans cesse — vous revenez, vous dérivez, vous revenez encore — et cela trahit un esprit instable. Il y a un risque dans toute cette hésitation, mais aucun dommage durable.",
    "Tout le monde autour de vous va dans un sens, et vous seul faites demi-tour vers ce qui est juste. À l'écart de la foule, votre retour solitaire est le vrai.",
    "Vous revenez avec un examen de conscience réel et honnête, en pesant votre propre conduite. À vous sonder ainsi, vous rentrez sans rien à regretter.",
    "Vous avez manqué le moment de faire demi-tour, et maintenant il est trop tard — cela cause un tort grave et durable. Avancez à partir de là et cela finit en déroute totale que vous paierez longtemps.",
  ],
  25: [
    "L'élan sincère est en marche, et il est net. Agissez maintenant, avant de vous en dissuader — l'instinct sans détour connaît le chemin.",
    "Faites le travail sans compter le gain. Labourez, livrez, répétez — et laissez les résultats venir à leur rythme au lieu de noter chaque pas.",
    "Parfois on encaisse un coup sans rien avoir fait : la perte tombe, la faute n'est pas la vôtre. Acceptez le prix sans détour et n'en faites pas de la culpabilité.",
    "Gardez ce qui est vraiment à vous et n'en demandez la permission à personne. Tenez votre ligne et vous ne pouvez pas vraiment vous tromper.",
    "Cet ennui n'est pas votre fait, et il n'a pas besoin d'être réglé. Cessez d'y toucher, laissez-le, et il se dissipe tout seul.",
    "Forcer le bon geste au mauvais moment fait des dégâts. Même quand vous avez clairement raison, restez immobile — le moment interdit le pas.",
  ],
  26: [
    "Il y a un danger devant, alors arrêtez-vous. Ne forcez pas le passage par principe — acceptez le frein et patientez.",
    "La chose cale d'elle-même — le projet perd son élan sans que vous le forciez. Aucun tort à renoncer quand la dynamique s'éteint.",
    "La voie s'ouvre et vous pouvez courir, mais ne vous relâchez pas. Restez sur vos gardes chaque jour, restez vif, et il est bon d'avoir où aller.",
    "Réglez le problème avant qu'il durcisse — posez la limite tant que les cornes du jeune taureau sont encore tendres. Endiguer le mal à la source, voilà la vraie victoire.",
    "Domptez la force dangereuse à la racine, sans l'affronter de face. Neutralisez ce qui la rend dangereuse et elle s'apaise — bonne fortune.",
    "La voie s'ouvre enfin en grand. Tout ce que vous avez emmagasiné et retenu se libère enfin, et avance sans résistance.",
  ],
  27: [
    "Vous laissez filer votre propre façon de vous nourrir pour rester à envier ce qu'a quelqu'un d'autre. Convoiter son assiette pleine depuis un manque, c'est un mauvais calcul.",
    "Vous quémandez du soutien aux mauvais endroits — vous appuyant sur plus bas que vous, ou mendiant en haut ce que vos pairs devraient donner. Hors route, et ça finit mal.",
    "Vous nourrir à contre-courant de votre propre nature sonne creux, même en vous y accrochant. Lâchez prise pour longtemps ; rien ici ne rapporte.",
    "Vous tourner vers ceux d'en bas pour du soutien convient ici, et la faim est vive — le regard fixe du tigre. Désirez-le intensément ; vous restez net.",
    "Sortez du chemin habituel, restez en place et tenez bon — voilà le geste stable et heureux. Sachez seulement que ce n'est pas l'heure de la grande traversée.",
    "Vous êtes la source où d'autres puisent leur subsistance. Portez le poids, respectez le risque qui l'accompagne, et c'est bon — vous pouvez maintenant faire la grande traversée.",
  ],
  28: [
    "La charge est lourde, alors soyez méticuleux dès le départ — préparez le terrain avec autant de soin qu'un lit de joncs blancs sous une offrande. Tant de soin tôt vous garde net.",
    "Contre toute attente, la branche morte bourgeonne et le vieux s'allie au jeune : ce qu'on avait enterré revient à la vie. Saisissez-le ; c'est favorable.",
    "Vous portez plus que la structure ne peut tenir et elle plie jusqu'au point de rupture. Faire cavalier seul et s'entêter ici finit mal — trouvez du renfort ou allégez la charge.",
    "Étayez la chose surchargée et elle tient bon — bien. Mais si vous la soutenez pour un agenda caché à vous, c'est là que vient la honte.",
    "Un sursaut tardif et de surface — la vieille branche fleurit, l'union dépareillée se fait. Aucun vrai mal, mais aucun mérite durable non plus ; la floraison ne tiendra pas.",
    "Vous vous avancez par-dessus la tête et vous coulez. Ça vous coûte, mais vous n'êtes pas en faute — vous avez encaissé la perte en faisant ce qui était juste.",
  ],
  29: [
    "Vous êtes tombé dans le danger au cœur du danger, la fosse la plus profonde. C'est le fond, et c'est mauvais — vous avez perdu le chemin tout entier.",
    "Cerné de danger de tous côtés, ne tentez pas l'évasion spectaculaire. Visez un seul gain, petit et sûr, et faites un seul pas certain.",
    "Où que vous vous tourniez, danger devant et danger derrière. Ne bougez pas — toute action ici ne fait que vous enfoncer.",
    "Réduisez à l'essentiel — une cruche de vin, un bol de riz passés simplement par la fenêtre. Une sincérité honnête et sans fioritures vous fait passer net.",
    "Ne remplissez pas le trou à ras bord — amenez-le juste au niveau et arrêtez-vous là. Faites assez pour écarter le danger, pas plus, et il n'y a pas de faute.",
    "Ligoté et pris dans les ronces, mis à l'écart des années durant sans issue. C'est être profondément, durablement piégé — infortune.",
  ],
  30: [
    "La journée commence en désordre et vos pas s'emmêlent et se confondent. Avancez avec soin et respect dans le chaos du début et vous restez net.",
    "Vous brillez depuis un centre équilibré, stable et clair. C'est le rare éclat sans tache — fortune suprême.",
    "C'est la lumière du soleil couchant. Soit vous faites la paix et chantez, soit vous vous effondrez sur ce qui s'achève ; s'accrocher à ce qui doit s'éteindre, voilà l'infortune.",
    "Ça vient trop brusquement — une flambée qui éclate et meurt, rejetée aussi vite qu'elle a pris. Un feu sans discipline ne peut pas durer.",
    "Les larmes coulent et le chagrin se brise, mais la brûlure vous purifie. De l'autre côté d'une vraie peine, la bonne fortune suit.",
    "Frappez avec décision mais précision : éliminez les meneurs, épargnez ceux qui n'ont fait que suivre le mouvement. Une force ciblée, pas un massacre — et vous restez net.",
  ],
  31: [
    "L'attirance se sent à peine — un frémissement dans l'orteil, tout intérieur. L'intérêt est réel mais bien trop faible encore pour mettre quoi que ce soit en mouvement.",
    "L'attirance vous atteint et l'envie est de bondir en avant — n'en faites rien. Précipiter finit mal ; rester immobile et attendre est le bon geste.",
    "Vous bougez seulement parce que vous suivez la foule, comme des cuisses qui vont où va le corps. Emboîter le pas et s'accrocher aux autres devient humiliant.",
    "Tenez le cap et ça paie — le regret se dissipe. Mais si votre cœur ne cesse de vaciller dans une agitation inquiète, peu suivront votre dessein flottant.",
    "Le lien reste bloqué en haut, dans la nuque raide, sans jamais atteindre le cœur. C'est superficiel et ça ne bougera guère — mais au moins rien ici ne tourne mal.",
    "Tout est dans la mâchoire — joues, langue, pur discours et persuasion. Rien que des mots, sans vrai mouvement dessous.",
  ],
  32: [
    "Vous forcez la permanence dès le premier jour, exigeant le résultat de long terme avant que la chose ait eu le moindre temps. Pousser aussi fort maintenant finit mal et ne gagne rien.",
    "Tenez le centre stable et le regret se dissout. Votre force est à la mesure du moment — continuez exactement ainsi.",
    "Sans foyer stable pour vos principes, vous ne cesserez de vous attirer la honte. Le revirement n'est pas la liberté ; vous accrocher à cette inconstance ne fait qu'apporter la honte.",
    "Vous peinez depuis longtemps sur un terrain sans gibier — un effort constant pointé au mauvais endroit. La persévérance sur une piste morte ne donne rien ; déplacez-la.",
    "Suivre fermement une seule voie fixée convient à celui dont le rôle est de suivre, mais dessert celui qui doit peser chaque cas à neuf. Ajustez la règle à votre rôle.",
    "Une endurance qui n'est que remous et ne se pose jamais n'en est pas une. Sans cesse agité et jamais au repos, cela finit mal — ce qui ne peut se reposer ne peut durer.",
  ],
  33: [
    "Vous avez trop attendu pour reculer, et vous voilà à découvert. Ne forcez pas l'avancée ; restez immobile, n'entreprenez rien.",
    "Tenez votre position avec une résolution calme et inébranlable. Rien ni personne ne peut vous en déloger.",
    "Vous ne pouvez pas vous retirer proprement, trop de choses dépendent de vous. Praticable pour les petites affaires, mais aucun moyen de mener quoi que ce soit d'important.",
    "La force, ici, c'est de lâcher prise franchement. Partez sans vous accrocher, pendant que votre part la plus faible continue de se cramponner.",
    "Partez tant que la relation est encore chaleureuse. Sortez avant que tout ne s'aigrisse, et vous ne laissez rien de brûlé derrière vous.",
    "Vous êtes sorti, vous êtes au clair, et vous le vivez avec légèreté. Aucun regret, et la voie devant vous est grande ouverte.",
  ],
  34: [
    "Vous brûlez de foncer, mais vous n'en avez pas encore les moyens. Bouger maintenant se retourne contre vous.",
    "Une force qui garde la mesure, sans forcer l'avancée ni reculer. Restez constant et vous l'emportez.",
    "N'y allez pas en force brute. La force pour la force vous coince, empêtré dans votre propre élan.",
    "Le blocage cède et vous avancez avec une puissance énorme mais sans effort. Gardez votre discipline et le regret s'efface.",
    "Lâchez ce que vous serriez de trop près. Desserrez votre prise et tout se libère sans dommage.",
    "Vous êtes bloqué par votre propre poussée, coincé dans les deux sens. Voyez l'impasse clairement, prenez-en votre parti, et elle se dénoue avec le temps.",
  ],
  35: [
    "Vous avancez et on vous rabroue. Restez constant, ne forcez pas une confiance qu'on ne vous accorde pas encore, et tout ira bien.",
    "Une montée lente et décourageante. Tenez votre cap malgré tout, et la reconnaissance viendra de celui qui est au-dessus de vous.",
    "Tout le monde avance ensemble, en confiance. Le groupe étant aligné, la voie s'ouvre sans friction.",
    "Monter par des prises avides et furtives. Aussi bien que cela paraisse aller, cette voie-là est dangereuse.",
    "Cessez de compter vos gains et vos pertes. Avancez ouvertement et cela se met en place.",
    "Tournez la force vers l'intérieur et mettez d'abord de l'ordre chez vous. Rude mais juste ; ne vous appuyez simplement pas dessus trop longtemps.",
  ],
  36: [
    "Au début d'une passe sombre, vous encaissez un coup et vous avez faim. Continuez vers votre but malgré les critiques.",
    "Vous êtes blessé, mais pas estropié. Agissez vite pour vous dégager, et la fuite tient.",
    "Vous pouvez frapper à la vraie source du mal, mais n'attendez pas de tout remettre d'aplomb d'un coup.",
    "Vous approchez assez près pour voir à quel point c'est pourri. Puis vous sortez sans bruit.",
    "Pris au piège près des ténèbres, cachez votre éclat mais gardez votre résolution intacte. La persévérance vous porte.",
    "Celui qui projetait l'ombre est monté haut, puis s'est effondré. Des ténèbres aussi totales finissent par se consumer elles-mêmes.",
  ],
  37: [
    "Fixez des règles claires tôt, avant que les mauvaises habitudes ne s'enracinent. Une structure en amont garde l'ensemble sain.",
    "Ne courez pas après vos propres impulsions. Faites le travail régulier et ingrat qui maintient tout nourri et en marche.",
    "Tenir bon sur les exigences, même avec rudeur, vaut encore mieux que de tout laisser glisser dans la plaisanterie. Un peu de friction maintenant sauve l'ensemble.",
    "Celui qui enrichit le groupe avec constance en est le vrai atout. Une grande fortune naît de ce soin discret.",
    "Menez par la confiance, pas par la peur. Quand les gens ne sont pas anxieux autour de vous, tout le monde est à l'aise.",
    "La sincérité tenue jusqu'au bout vaut un respect durable. C'est la constance qui finit par les convaincre.",
  ],
  38: [
    "Ne courez pas après ce qui s'en est allé ; cela revient de soi-même. Et quand vous croisez des gens mal intentionnés, restez simplement prudent.",
    "Une rencontre imprévue et informelle ressoude la brèche. Aucune faute à saisir un hasard quand les deux veulent renouer.",
    "Tout est bloqué et c'est humiliant au départ. Début difficile, mais cela s'arrange à la fin.",
    "Coupé de tout et seul, vous trouvez un allié sincère. Risqué encore, mais s'unir de bonne foi dissipe le reproche.",
    "La barrière qui vous sépare de votre allié s'effondre. Allez à sa rencontre ; ce n'est pas une erreur.",
    "Vous avez pris un allié pour un ennemi. Lâchez le soupçon, voyez qu'il est de votre côté, et la tension cède enfin.",
  ],
  39: [
    "Vous enfoncer dans le blocage vous coince. Choisir d'attendre et de faire demi-tour maintenant, c'est ce qui force le respect.",
    "Vous heurtez mur après mur, mais c'est pour le devoir, pas pour vous. Ne fléchissez pas ; tenez bon.",
    "N'avancez pas dans le blocage. Revenez, et ceux qui comptent sur vous sont heureux de votre retour.",
    "Plutôt que de forcer seul en avant, repliez-vous et rassemblez ceux qui partageront la route difficile.",
    "Au point le plus profond de la difficulté, en tenant ferme au centre, le secours arrive.",
    "Ne forcez pas vers l'extérieur ; revenez prêter votre force là où elle est nécessaire, et cherchez un conseil avisé. Cela accomplit beaucoup.",
  ],
  40: [
    "La tension vient de se rompre. Reposez-vous, n'en faites pas plus ; il n'y a rien d'autre à dire.",
    "Débarrassez-vous de la ruse et de la fausseté autour de vous, et tenez un cap droit. C'est cela qui l'emporte.",
    "Étaler une position que vous n'avez pas méritée attire les ennuis. Ce déploiement déplacé apporte l'humiliation.",
    "Lâchez l'attache basse et indigne. Alors seulement les gens dignes de confiance s'approchent.",
    "Une fois que vous coupez vraiment les amarres, les esprits mesquins s'éloignent d'eux-mêmes. Se libérer, c'est tout le propos.",
    "Éliminez l'obstacle bien installé d'un seul coup décisif et bien préparé. Plus rien ne vous retient.",
  ],
  41: [
    "Aider quelqu'un, c'est très bien, et ça vaut même qu'on lâche son propre travail — mais mesurez d'abord le prix. Donnez sans réserve, jamais au point de vous épuiser.",
    "Pour donner le plus, donnez sans vous vider. Tenez votre position ; ne vous surmenez pas, ou vous perdez justement ce dont l'autre a besoin.",
    "À trois on est de trop : il faut que l'un parte. Réduisez au vrai partenariat ; la bonne configuration se trouve d'elle-même dès que vous cessez de forcer le troisième.",
    "Coupez ce qui vous pesait, et les gens accourent, heureux d'aider. Délestez-vous du fardeau et regardez le soutien arriver.",
    "Une offre ou une aubaine survient, que nul ne peut contester — tous les signes pointent au même endroit. C'est le oui rare et limpide.",
    "Vous élevez les autres sans rien leur coûter, et l'aide vient de partout. La vraie générosité n'est pas une soustraction ; les anciennes limites cessent de compter.",
  ],
  42: [
    "C'est le moment du grand geste — le soutien vous arrive d'en haut, alors frappez fort. Ici, l'action audacieuse paie sans accroc.",
    "Un accroissement survient, irréversible, confirmé de tous côtés. Restez ferme et engagé ; même vos efforts modestes sont bénis.",
    "La croissance passe, curieusement, par un revers — un coup dur qui finit par aider. Restez honnête, tenez le milieu, rendez compte simplement, et vous n'encourez aucun blâme.",
    "Tenez la ligne médiane et vos conseils sont entendus tout en haut. Vous avez gagné assez de confiance pour faire bouger les gens et changer la manière de mener.",
    "Menez avec une bienveillance sincère et n'attendez rien en retour. La bonté elle-même est ce qui se voit reconnu — voilà tout le bénéfice.",
    "Vous prenez et ne donnez rien ; alors les gens se retournent contre vous. Un cœur instable et intéressé, voilà ce qui a attiré l'ennui.",
  ],
  43: [
    "Pressé de foncer sur la seule assurance, mais si vous ne pouvez pas vraiment gagner, l'élan devient la faute. N'avancez pas sur une force que vous n'avez pas.",
    "Restez en alerte et sonnez l'alarme, même la nuit. Vous n'avez pas à craindre — vous l'avez vu venir et vous êtes prêt.",
    "Afficher trop ouvertement sa résolution sur son visage attire l'ennui. Suivez seul votre chemin à travers le désordre, encaissez la boue et le ressentiment, et vous en sortez net malgré tout.",
    "Vous êtes bloqué et vous trébuchez, et vous laisser guider arrangerait tout — mais vous refusez l'aide. Le conseil est juste là ; vous n'y croyez simplement pas.",
    "Arrachez le problème qui traîne avec résolution, comme on désherbe. Tenez le milieu, n'allez pas aux extrêmes, et il n'y a aucun blâme.",
    "Vous vous arrêtez avant la fin et sautez le dernier avertissement — et c'est là que tout dérape. Le dernier reste du problème est précisément ce que vous ne pouvez pas ignorer.",
  ],
  44: [
    "Attrapez-le tout de suite, dès le départ, par un arrêt ferme. Contenez-le tôt et tout va bien ; laissez-le filer et une petite chose part en tous sens, hors de contrôle.",
    "Vous avez contenu le problème en silence — très bien pour l'instant. Mais ne cherchez pas à le refiler aux autres ni à le partager ; gardez-le là où il est tenu.",
    "Vous êtes bloqué et la marche est rude, sans bon appui. Restez conscient du danger et vous évitez une vraie erreur.",
    "Vous avez perdu le contact avec ceux d'en dessous, et maintenant il n'y a plus rien là. Ce lien rompu, voilà ce qui amène l'ennui.",
    "Gardez votre vraie force cachée et sans contrainte, comme un fruit sous les feuilles. Ne saisissez rien ; ce qui vous est destiné arrive de soi-même.",
    "Vous abordez chacun raide, cornes en avant, vous tenant au-dessus. Personne n'est vraiment à blâmer sauf vous — c'est juste une manière d'être isolante et embarrassante.",
  ],
  45: [
    "Votre engagement vacille et le groupe se disperse. Parlez — une seule main tendue avec sincérité transforme le désordre en soulagement. Avancez sans crainte.",
    "Laissez-vous attirer dans le groupe au lieu de résister. Un petit geste sincère suffit pour en faire partie.",
    "Vous voulez en être mais restez à l'écart, à soupirer en marge. Joignez-vous quand même — un peu de gêne, mais aucun vrai dommage.",
    "Les grands résultats viennent quand vous rassemblez les gens pour le bien commun, pas pour bâtir votre propre clientèle. Lâchez l'intérêt personnel et ça marche.",
    "Occuper une place de chef, c'est très bien, mais si la confiance n'est pas encore là, seule une constance patiente et durable dissout le doute. Méritez-la avec le temps.",
    "Vous vous affligez d'être tenu à l'écart, jusqu'aux larmes. Persistez — ceux qui souffrent sincèrement de ne pas en être finissent par trouver leur place.",
  ],
  46: [
    "Vous montez avec un vrai soutien et on vous accueille là-haut. Le terrain est favorable — c'est un excellent début d'ascension.",
    "Vous n'avez pas grand-chose à offrir, mais offert avec sincérité, c'est accepté. Présentez-vous honnête et modeste ; pour l'instant, cela suffit.",
    "La voie devant est grande ouverte, une ville déserte, sans résistance. Avancez librement — rien ne vous barre le chemin.",
    "Votre ascension est reconnue et consacrée par ceux d'en haut. La montée est légitime désormais — bonne fortune, aucun blâme.",
    "Continuez de monter, une marche réfléchie à la fois. La persévérance régulière dans l'escalier, voilà ce qui amène le bon résultat — ne vous précipitez pas.",
    "Monter à l'aveugle dans le noir, juste pour continuer de monter. La seule chose qui sauve la situation maintenant, c'est une vigilance sans relâche pour ne pas perdre la voie.",
  ],
  47: [
    "Usé et isolé, coincé dans un lieu sombre, sans personne en vue pour longtemps. C'est l'épuisement au plus bas — attendez que ça passe.",
    "Vidé alors même que le confort vous entoure, mais le soulagement et la reconnaissance approchent. Faites l'offrande, restez en place ; forcer la sortie maintenant se retourne contre vous, même si vous n'êtes pas en faute.",
    "Vous vous acculez contre la pierre et vous agrippez aux épines, puis vous rentrez pour trouver votre appui parti lui aussi. Forcer ici ne fait qu'empirer les choses.",
    "L'aide vient, mais lentement et maladroitement — coincée dans un confort emprunté. C'est humiliant, mais l'affaire finit tout de même par aboutir.",
    "Abattu et entravé même par ceux qui devraient aider, le soulagement ne vient que peu à peu. Ne forcez pas ; c'est l'offrande discrète et patiente qui fonctionne.",
    "Empêtré et chancelant au bord du gouffre, épuisé. Le tournant arrive à l'instant où vous admettez que les vieilles manières mènent au regret — reconnaissez-le, changez, et aller de l'avant paiera.",
  ],
  48: [
    "Vous êtes une source stagnante et négligée — rien de frais, personne qui y puise. Quand vous cessez de vous renouveler, les gens cessent de venir.",
    "Vous visez petit, à courir après le menu fretin, et votre seul outil est fêlé et fuit. L'effort se perd parce que les moyens sont brisés — réparez l'essentiel.",
    "Vous avez fait le nettoyage et la valeur est réelle, mais personne n'y puise — un gâchis qui pique. Le travail est solide ; ce qui manque, c'est quelqu'un d'assez lucide pour s'en servir.",
    "Vous consolidez les fondations, doublant le puits de pierre. Pas glorieux, mais aucun blâme — réparer la source, c'est du temps bien employé.",
    "La source est claire, fraîche et prête — pleinement utilisable. Tout est en place pour y puiser maintenant.",
    "On y puise librement et elle n'est jamais scellée — la source reste ouverte à tous. C'est là tout l'enjeu : fiable, généreuse, et c'est là qu'est la vraie bonne fortune.",
  ],
  49: [
    "Les raisons de changer sont réelles, mais le moment ne l'est pas. Vous êtes retenu pour une raison — tenez, ne lancez rien encore.",
    "Le bon jour est enfin arrivé. Faites le changement maintenant : avancez et vous êtes au clair, sans rien à regretter.",
    "Forcer le changement le fait exploser ; rester dessus est dangereux aussi. Une fois que l'idée a tourné assez longtemps pour gagner la confiance, alors agissez.",
    "On y croit, maintenant, alors le doute s'est dissipé. Renversez l'ancienne manière à cet instant et tout se passe bien.",
    "Vous changez si nettement, si visiblement, que personne n'a besoin d'être convaincu — la nouvelle direction est évidente et on y adhère d'emblée.",
    "Vous affinez le nouvel ordre jusqu'à le rendre impeccable ; les autres ne font que ravaler la façade. N'en demandez pas plus maintenant — installez-vous et tenez la ligne gagnée.",
  ],
  50: [
    "Videz les vieux résidus avant de remplir à nouveau. Ce qui ressemble à jeter quelque chose d'indigne n'est que vider un dépôt rance pour que le vrai travail puisse commencer.",
    "Votre récipient est plein et le travail est solide. Les rivaux vous envient mais ne peuvent vous atteindre — restez concentré et tout se passe bien.",
    "Votre valeur reste inutilisée parce que le lien est rompu et que personne ne peut porter le travail. Réparez le lien, et une fois dégagé, cela finit bien.",
    "Vous avez pris plus que vous ne pouviez tenir et ça a débordé — la confiance qu'on vous a faite est gâchée. C'est la honte de ne pas être à la hauteur de la tâche.",
    "Vous avez les bonnes personnes et des moyens solides pour porter le travail. Restez rigoureux et juste, et cela tient.",
    "Tout est en place — fort, raffiné, fiable. C'est le sommet où rien ne joue contre vous ; allez-y.",
  ],
  51: [
    "Le choc frappe et vous paniquez, puis ça passe au soulagement et même au rire. Bien — la frayeur a aiguisé votre vigilance au lieu de vous briser.",
    "Une secousse frappe et vous croyez avoir perdu quelque chose de précieux, alors vous vous repliez vers l'abri. Ne courez pas après ; ce qui est parti revient de soi avec le temps.",
    "La perturbation vous laisse ébranlé et déséquilibré. Si l'alerte vous met en mouvement dans la bonne direction, il n'en sort aucun mal.",
    "Le choc tombe et vous restez bloqué — enlisé dans l'inertie, incapable de réagir tant que vous croupissez là.",
    "Les perturbations affluent de tous côtés, mais rien d'essentiel n'est perdu. Restez sur le travail qu'on ne peut pas lâcher.",
    "Le coup sème le chaos et vous êtes figé — avancer maintenant se retourne contre vous. Il a frappé un proche, pas encore vous, alors aucune honte à temporiser, même si d'autres ronchonnent.",
  ],
  52: [
    "Arrêtez-vous avant d'avoir fait le premier pas. Aucun mal à ne pas commencer — gardez seulement cette retenue ferme.",
    "Vous vous retenez, mais quelque chose de plus grand vous entraîne sans que vous puissiez l'arrêter, et cela vous laisse mal à l'aise et plein de ressentiment.",
    "Vous forcer à vous arrêter en vous crispant à l'extrême ne fait que tendre et grincer — cette retenue à s'en faire blanchir les jointures vous ronge.",
    "Vous vous mettez au repos et apaisez le corps. Aucun mal, même si le calme ne vous a pas encore traversé de part en part.",
    "Retenez vos paroles pour qu'elles sortent mesurées et ordonnées. Le regret disparaît.",
    "Une immobilité qui vient d'un véritable achèvement, sans effort. C'est le calme posé de ce qui est accompli, et cela se passe bien.",
  ],
  53: [
    "Vous arrivez à peine et vous êtes exposé — débutant, critiqué, sur un terrain instable. Il y a du risque et des rumeurs, mais aucune vraie faute là-dedans.",
    "Vous avez gagné un terrain plus sûr et pouvez vous reposer, manger, vous installer dans le travail sereinement. Cela se passe bien.",
    "Vous dépassez votre rayon sûr : vous foncez et ne revenez pas, ou vous lancez ce qui ne portera pas de fruit. Cela tourne mal — concentrez-vous sur la défense de ce que vous avez.",
    "Vous atterrissez sur un terrain qui n'est pas vraiment le vôtre, mais vous l'acceptez avec patience comme un lieu de repos provisoire. Aucun mal à vous en accommoder.",
    "Vous êtes près du sommet, et longtemps rien ne semble en sortir. Mais au final rien ne peut bloquer le résultat — cela aboutit enfin.",
    "Vous atteignez les hauteurs, et même ce que vous laissez tomber devient utile aux autres. Cela se passe bien ; la longue montée arrive quelque part qui a du sens.",
  ],
  54: [
    "Vous arrivez d'une position inférieure, avec peu de marge pour agir. Travaillez dans ces limites et servez là où vous le pouvez, et cela se passe quand même bien.",
    "Vous ne voyez la situation qu'à moitié, et on vous néglige. Tenez ferme et gardez la foi, même depuis ce coin obscur et oublié.",
    "Vous vouliez le meilleur arrangement mais avez dû attendre dans un rôle moindre, et ce n'est qu'en acceptant la place plus humble que vous trouvez une voie. L'attente orgueilleuse n'allait jamais tenir.",
    "Vous laissez passer le moment exprès ; la bonne occasion viendra en son temps. Mieux vaut attendre la bonne que saisir la mauvaise maintenant.",
    "La vraie valeur n'a pas besoin de se montrer — votre substance éclipse les présentations plus tape-à-l'œil. Comme la lune juste avant la pleine, c'est à peu près le mieux qu'on puisse espérer.",
    "Toutes les formes sont respectées mais il n'y a rien dedans — panier vide, rituel sans âme. Faire les gestes sans substance ne mène nulle part.",
  ],
  55: [
    "Vous rencontrez un vrai pair, un égal en envergure. Même un temps intense et concentré ensemble n'est pas une erreur — avancez avec lui et cela vous vaut de la reconnaissance.",
    "Tout est devenu si trouble que vous n'y voyez plus clair même au moment évident ; pousser maintenant ne fait que nourrir la suspicion. Laissez plutôt transparaître votre honnêteté, et cela tourne bien.",
    "L'obstruction est si épaisse que vous distinguez à peine quoi que ce soit, et vos moyens d'agir sont brisés. Aucune faute — vous êtes vraiment incapable pour l'instant, pas réticent.",
    "Vous étiez dans le noir, mais voilà que vous rencontrez quelqu'un de votre trempe qui l'éclaircit. C'est la rencontre qui renverse la situation.",
    "Des gens capables se présentent et vous apportent soutien et éloges. Cela se passe bien.",
    "Vous vous laissez murer par la grandeur jusqu'à ce que votre propre maison soit vide et que plus personne n'y soit passé depuis longtemps. Voilà l'échec — une ampleur qui creuse le vide dans la vie qu'elle abrite.",
  ],
  56: [
    "Vous n'êtes pas dans votre élément, alors vous tracasser sur des détails et des broutilles est exactement la façon d'attirer les ennuis sur vous. Ne vous prenez pas la tête pour des riens ici.",
    "En terrain inconnu, vous gardez vos ressources près de vous et gagnez la loyauté de quelques personnes fiables. C'est ainsi qu'on trouve un appui stable dans un endroit étranger.",
    "Vous incendiez votre propre abri et perdez ceux qui vous aidaient. Insister maintenant est tout simplement dangereux — vous avez détruit votre base par négligence.",
    "Vous trouvez un lieu où vous reposer et un peu de sécurité et de moyens pour vous protéger, mais quelque chose cloche. La sécurité est inconfortable parce qu'elle n'est pas vraiment la vôtre.",
    "Vous tentez votre chance et, même si cela vous coûte quelque chose, le talent que vous montrez vous vaut reconnaissance et statut. Un don bien exposé attire les faveurs même loin de chez soi.",
    "Vous prenez vos aises et vous riez, puis tout brûle et vous voilà à pleurer — vous perdez l'essentiel par négligence. Quand vous êtes l'étranger, oublier de rester humble est ce qui vous perd.",
  ],
  57: [
    "Vous avancez puis reculez sans cesse, dans l'incertitude. Arrêtez d'hésiter : fixez une intention ferme et laissez la discipline, et non l'humeur, stabiliser la décision.",
    "Quelque chose se cache sous la surface. N'avancez pas seul : faites appel à des gens qui voient ce qui vous échappe, et posez la question franchement.",
    "Répéter sans cesse la même chose, ce n'est plus de la persévérance, c'est du harcèlement. Dites-le une ou deux fois, puis faites confiance au message pour porter.",
    "Le doute se dissipe. Votre poursuite patiente et régulière finit par payer pleinement : vous rapportez plus que prévu d'un long effort.",
    "Tenez le cap et l'inquiétude s'efface. Le début a été brouillon, mais l'aboutissement est réel ; planifiez bien avant et après le mouvement, et tout se met en place.",
    "Vous creusez encore le même problème, mais vous avez épuisé vos outils et vos appuis. Insister vous coûte sans rien rapporter : partez.",
  ],
  58: [
    "Un contentement calme et installé, sans soif de plus. Vous êtes en paix avec vous-même, et c'est précisément là que les choses tournent bien.",
    "Une vraie joie qui vient de l'intérieur, pas de l'approbation des autres. Fiez-vous-y : elle dissipe les doutes et vous oriente droit.",
    "Chercher le plaisir au dehors, s'agiter pour être diverti et flatté, ne mène nulle part. Cessez de le courtiser : il ne vous comblera pas.",
    "Tiraillé entre deux plaisirs, vous ne trouvez pas le repos. Tranchez clairement, coupez celui qui vous nuit, et le soulagement est immédiat.",
    "S'appuyer sur ce qui vous épuise à petit feu est un vrai danger. Protégez votre fermeté contre le confort qui, en réalité, la ronge.",
    "Un charme qui n'existe que pour séduire et appâter, tout en surface, sans vérité, ne se pose jamais sur du solide. Ne soyez pas ce numéro, et n'y tombez pas.",
  ],
  59: [
    "Traitez la brouille tant qu'elle est petite, et faites-le vite et fort. Rattrapez le malentendu ou la fissure avant qu'ils ne durcissent, et tout va bien.",
    "Quand les choses commencent à se déliter, dirigez-vous vite vers ce qui vous stabilise. Trouvez votre appui, votre refuge, et le regret s'efface.",
    "Dissolvez votre propre ego et vos petites préoccupations. Tournez-vous vers les autres, cessez de protéger votre petit moi, et il n'y a rien ici à regretter.",
    "Défaites votre propre clan et la loyauté envers votre cercle étroit. De cette dispersion naît une alliance bien plus vaste que vous n'auriez pu prévoir.",
    "Diffusez le message largement et dépensez ce que vous avez thésaurisé pour le bien commun. En période de délitement, menez avec constance et vous restez net.",
    "Mettez-vous hors de portée d'un vrai danger : dispersez la menace avant que le sang coule et prenez vos distances. Éviter la blessure n'a rien de blâmable.",
  ],
  60: [
    "Vous n'avez pas à franchir chaque ligne ni à saisir chaque ouverture. Savoir quand rester en place et ne rien faire est une discipline en soi : tenez-vous tranquille.",
    "Vous vous êtes retenu alors qu'il fallait bouger. La retenue passé son heure n'est plus de la prudence, c'est de la paralysie, et ici elle vous coûte l'occasion.",
    "Refuser toute limite, et les excès et la dépense vous rattrapent en regrets. Ne cherchez pas de coupable : celui-là, c'est vous.",
    "Des limites que vous portez sans effort, sans tension ni ressentiment. Quand la discipline paraît naturelle plutôt que subie, elle vous mène au succès.",
    "Une retenue que vous adoptez vraiment, et même appréciez, vous attire le respect. Continuez avec cette autodiscipline souple et elle vous vaut des honneurs.",
    "Des limites dures, sans joie, qui se punissent elles-mêmes ne tiennent pas. Vous acharner ainsi se retourne contre vous : relâchez, et le regret finira par passer.",
  ],
  61: [
    "Soyez vraiment posé et préparé au-dedans, et tout va bien. Mais si vous visez quelqu'un en secret, votre propre cœur ne vous laissera pas en repos.",
    "La vraie sincérité résonne même quand personne ne regarde. Parlez avec franchise à la bonne personne et on vous répondra de même : nul besoin de jouer un rôle.",
    "Lier toute votre humeur à quelqu'un d'autre vous fait osciller entre l'euphorie et le chagrin. Ancrez-vous, ou chaque éclat et chaque silence vous ballotteront.",
    "Le moment est venu de quitter vos compagnons médiocres et de vous élever vers la voie plus haute, même s'il faut continuer seul. Couper ces liens n'a rien de blâmable.",
    "Une sincérité si solide qu'elle relie les gens comme une corde. Votre intégrité maintient l'ensemble en place : gardez-la ferme et il n'y a rien à reprocher.",
    "Beaucoup de bruit et aucune substance, à forcer pour avoir l'air impressionnant sans rien derrière. Le vacarme creux ne dure pas : continuez de faire semblant et cela finit mal.",
  ],
  62: [
    "Viser bien au-delà de vos forces dès le départ. Vous surestimer à ce point, avant d'avoir rien bâti, vous fait chuter : commencez petit.",
    "Visez un peu plus bas que votre cible grandiose et vous atteindrez ce qui est réellement à portée. Restez modeste et bien proportionné, et tout va bien.",
    "Baissez la garde maintenant et vous serez frappé par-derrière. C'est un moment qui appelle un surcroît de prudence, pas d'assurance : surveillez vos arrières.",
    "Rien à reprocher, mais ne forcez pas le passage. Insister est dangereux : tenez ferme, restez en place et gardez votre retenue plutôt que d'agir.",
    "Gros nuages, toujours pas de pluie : les conditions ne sont pas là pour aboutir. Acceptez que de faibles moyens ne finissent pas un grand chantier ; prenez le gain modeste et accessible.",
    "Aller toujours plus loin au-delà du but, s'envoler sans aucun point de chute. C'est une ruine que vous vous infligez : reculez avant de ne plus le pouvoir.",
  ],
  63: [
    "Le travail est fait et vous êtes tenté de foncer. Freinez plutôt au moment de la traversée : vous retenir maintenant vous évite des ennuis.",
    "Vous avez perdu quelque chose sur quoi vous comptiez. Ne le poursuivez pas : laissez-le partir, tenez votre cap, et il vous reviendra de lui-même avant longtemps.",
    "C'est une longue campagne éreintante qui prend des années à gagner. Ne l'entreprenez qu'avec la profondeur et l'endurance qu'elle exige : ce n'est pas une décision à la légère.",
    "Même votre travail le plus abouti laisse apparaître des fuites. Restez attentif toute la journée : les coutures se relâchent en silence, alors colmatez au fur et à mesure.",
    "Un effort modeste et sincère vaut mieux qu'un effort fastueux et creux. Ne dépensez pas plus que le rival : soyez plus sincère ; l'intention vraie pèse plus que le grand étalage.",
    "Forcer au-delà de la ligne d'arrivée vous noie. Le danger, maintenant, c'est de prendre le sommet pour un lieu de repos et de continuer à grimper : arrêtez-vous une fois fini.",
  ],
  64: [
    "Vous n'êtes pas encore assez fort, et traverser maintenant ne fait que vous embourber et vous couvrir de honte. Attendez d'avoir vraiment rassemblé vos forces.",
    "Levez le pied et retenez-vous pour l'instant. Garder cette retenue, au lieu de vous jeter sur ce qui n'est pas fini, est exactement ce qu'il faut.",
    "Vous lancer tout de suite, avant que le moment ne soit mûr, tourne mal. Mais une fois les conditions réunies, c'est précisément l'instant de faire la grande traversée.",
    "Tenez le cap et le regret s'efface. C'est un effort dur, étalé sur des années, qui demande une vraie force : menez-le à terme et les fruits viennent.",
    "Tenez ferme et tout va bien, sans regrets. Votre clarté est sincère, et mener avec cette lumière vraie et franche est ce qui fait que cela marche.",
    "Presque arrivé, vous pouvez souffler et fêter un peu : c'est permis. Mais perdez la tête dans l'excès et vous jetez la discipline qui vous a mené jusqu'ici.",
  ],
};
