/**
 * The "Now" layer for the changing lines — a modern reading of each moving line.
 *
 * Keyed by King Wen number (1..64); each value is 6 strings, bottom→top (index 0
 * = line 1). Original content, faithful to each line's classic meaning, in the
 * same present-day voice as the hexagram-level readings (see now.ts). English
 * for now — a French translation is a follow-up.
 */
export const NOW_LINES: Record<number, string[]> = {
  1: [
    "The potential is real, but it's not time. Stay underground, keep building in private, and don't make your move yet.",
    "You're starting to be seen, and the work has real shape. This is the moment to find a mentor or someone of genuine stature.",
    "Relentless push all day, still alert at night — high pressure and real risk. Hold your integrity through it and you come out clean.",
    "You're at a fork: leap or hold. Either is fine if the choice is honest and yours, not driven by fear or show.",
    "You're in full command of your powers and visible at the top. Use the reach well: back real talent and let your influence do work.",
    "You've overreached, and there's nowhere up from here. Pride at the peak is the setup for the fall — pull back before it pulls you.",
  ],
  2: [
    "The first frost warns of the ice to come. Notice the small early sign now, because little things harden into big conditions if ignored.",
    "When you're grounded and square with reality, you don't have to scheme. Act straight from that base and things move without forcing.",
    "Do the work without grabbing credit. Stay quiet, finish what you were asked to finish, and let the recognition find you later.",
    "In a tense, watched moment, say nothing and reveal nothing. Hold the bag shut — no praise, no blame, just keep your counsel.",
    "Real substance worn quietly, never flashed, is what earns the most. Stay centered, stay modest, and let the worth show itself.",
    "When you fight the stronger force head-on as if you're equals, you both get hurt. Don't escalate into a battle nobody survives clean.",
  ],
  3: [
    "The launch is jammed and pushing harder won't clear it. Pause, line up allies and your footing, and prepare the ground for the real start.",
    "Obstacles keep stacking and the deal won't close yet. Don't force the commitment now — wait until conditions actually ripen, even if it's slow.",
    "Chasing the target with no guide just gets you lost deeper. Read the signs, let this one go; forcing ahead only buys humiliation.",
    "You've stalled out, but now's the time to reach for help. Go find the right partner openly — that's what opens the way forward.",
    "You can't deliver the big thing yet because circumstances won't allow it. Give in small ways, stay steady; overreaching now backfires.",
    "It's fallen apart and can't be held. Stop dragging the dead weight, let it go — the grief is real, but releasing it is the only way out.",
  ],
  4: [
    "Set a clear boundary early to break the bad pattern, then ease off. Keep punishing past the lesson and you just harden the resistance.",
    "Be patient and generous with the inexperienced. Take them in like your own, teach without contempt, and the whole team steadies.",
    "Don't tie yourself to someone who loses their head and their own footing at the first shiny thing. You'll gain nothing from it.",
    "A mind that walls itself off from all correction just calcifies in its error. Closed to teaching, it earns only its own humiliation.",
    "Admitting you don't know is the opening, not the weakness. That honest beginner's stance is exactly what pulls the help toward you.",
    "Correct the mistake, don't go to war over it. Fend off the harm, stop short of cruelty — overcorrection becomes its own wrong.",
  ],
  5: [
    "You're well clear of the danger, so don't manufacture urgency. Stay with your routine and what's durable; just hold steady and stay clean.",
    "Trouble is getting closer and the chatter is starting. Expect minor friction and petty criticism — ride it out, it still ends well.",
    "You've pushed in too close and you're stuck in the muck, inviting trouble. Drop the pace, stay watchful, and you keep the damage small.",
    "You're in the pit now, in over your head. Don't thrash — stay calm and yielding, and you get carried back out of it.",
    "Take the break in the middle of the grind: eat, rest, recover. Hold steady through the pause and you'll have strength for what's left.",
    "Right when it looks worst, unexpected help shows up. Treat the people you didn't ask for with respect, and the bad turn becomes a good one.",
  ],
  6: [
    "Drop the dispute early. There'll be a little gossip, but let it rest now and the whole thing dissolves instead of festering.",
    "You can't win this fight, so step back and disengage quietly. Yield in time and the people who depend on you take no damage.",
    "Lean on the solid reputation you've already built and just hold your ground through the risk. If you're serving someone else's cause, claim none of it.",
    "You can't win the contest, so stop. Accept how it actually is, change your mind, and find your footing again in doing what's right.",
    "Take it to a fair, impartial arbiter. When the right person weighs the matter on the merits, it gets settled cleanly — best outcome.",
    "Even if you win and grab the prize, you'll lose it again and again. A victory taken by force can't be held; the fight isn't worth it.",
  ],
  7: [
    "Start the effort with discipline and order from day one. Without that structure up front, even a good cause collapses into a mess.",
    "Lead from the middle of your people, not above them. Hold the center, earn their trust, and the backing from the top will confirm it.",
    "Don't let command get split or handed to the unfit — that's how the whole thing ends in bodies and ruin. One clear, capable lead.",
    "Pulling back and regrouping is not failure. Knowing when not to advance is itself a sign you actually know how to lead.",
    "Act on the clear opportunity in front of you — that's fair game, no blame. But put your most seasoned person in charge, not the untested one.",
    "When it's won, reward the people who earned it and build the new order. But don't hand real power to the wrong people, or you'll undo the win.",
  ],
  8: [
    "Join up with genuine sincerity and you stay clean. Be honestly full to the brim, and good fortune arrives from a direction you didn't expect.",
    "Let the alliance come from who you actually are, not from need. Bonds that grow out of your own real self hold without costing you yourself.",
    "Don't tie yourself to the wrong people. Loyalty spent on those who don't deserve it goes nowhere and drains you on barren ground.",
    "Commit to the worthy openly and out in the open, no hidden hedging. Backing good people plainly is what carries you forward.",
    "Lead the union without coercion: leave people a way out, like the hunt that drives game from three sides only. No one's cornered, and they stay willingly.",
    "An alliance with no real leader and no center falls apart. If the beginning was never set right, there's no good end to reach for.",
  ],
  9: [
    "Step back onto your own path — no shame in that. The right move is returning to what's genuinely yours, not chasing someone else's road.",
    "Someone ahead is doing it right, and their example pulls you back on track. Follow what fits; let the good model correct your course.",
    "Your push just snapped — wheels off, partners no longer aligned. The advance can't hold; something inside the project is quietly resisting, and forcing it breaks it.",
    "Be straight and the fear drains out. Pinned in a tight, risky spot, you've earned the trust of the people above you — and you're in the clear.",
    "You're sincere, so you bind people to you. Pull your closest ally in with honesty and share what you've got instead of hoarding it.",
    "Finally the payoff lands and you can rest — the slow effort worked. But don't push past this; pressing on now, when restraint did its job, only courts trouble.",
  ],
  10: [
    "Walk your plain path and move forward light. Stay content with simple and unencumbered, and you advance without anyone holding it against you.",
    "Keep to the level, quiet road. The one who stays low-key and steady, not chasing the spotlight, holds their footing and does well.",
    "Don't fake competence you don't have — the half-blind acting clear-eyed, the lame acting sure-footed get bitten. Overreaching your real ability brings the fall.",
    "You're stepping on the tiger's tail, but you do it carefully, fully aware of the danger. Handled with that much caution, it ends well.",
    "You act decisively and commit fully. Even when you're right, keep your sense of risk alive — firmness must not tip into recklessness.",
    "Look back over the whole path you walked and read what it tells you. When the full arc comes round complete, that's where the real fortune is.",
  ],
  11: [
    "Pull one good person in and a whole network comes up with them, roots entwined. Move now — the right people rise together and bring their own along.",
    "Carry the rough and untested, take the bold crossing, forget no one far off, and build no clique. That's how you walk the middle and keep it honest.",
    "Every flat stretch eventually slopes, every going-out turns back — nothing good runs forever. Stay steady through the hard turn, don't grieve, and enjoy what you've been given.",
    "You come down without flaunting what you have, drawing near your people in good faith. The one on top descends to meet the lower with an open, honest heart.",
    "The powerful gives the humble a real stake, and from that union comes deep good fortune. Lower yourself to lift another, and abundance follows.",
    "The wall crumbles back into the ditch. Don't send in force now; keep your decree within your own borders. However justified, regret comes — the good time has turned.",
  ],
  12: [
    "Pull one out and the whole network comes with them — but now hold steady and withdraw with your own kind. Keep faith quietly; this isn't the time to advance.",
    "They grit their teeth and endure; the small operators thrive on this, but you accept the standstill and find your way through. Don't get swept into the common tide.",
    "He swallows his shame in silence. People raised above their real ability are quietly tormented by a position they can't actually carry.",
    "You act on the highest mandate, and you're blameless; those who share your aim share the upside. The turn is starting to come.",
    "The deadlock is breaking and the strong come out ahead. But keep telling yourself 'it could still fail, it could still fail,' and tie your safety to something deeply rooted.",
    "The standstill is overturned: first the block, then relief. Nothing stuck stays stuck — no condition holds still forever.",
  ],
  13: [
    "Open fellowship right at the gate, in plain daylight. No blame — a partnership begun without secrecy or favoritism gives no one cause to object.",
    "Fellowship that only includes your own clique. That's a step down; binding yourself to a narrow inner circle falls short of the open, common ground.",
    "He stashes weapons in the bushes and climbs the hill to watch — and for three years can't make a move. Suspicion keeps him armed but paralyzed.",
    "You climb the wall but don't press the attack. Good — you back off the fight and yield to what's right.",
    "After bitter struggle, the ones meant to be together finally meet — first the tears, then the laughter. What truly belongs together can't be kept apart.",
    "Fellowship out in the open field, past the walls. No regret, even though it's not fully realized yet — the aim is sound even where the goal isn't reached.",
  ],
  14: [
    "You haven't touched anything harmful yet, so you're clean. Stay mindful that this could get hard and your good position holds — early on, it's still untested and easy to keep clear.",
    "A big wagon for the load and a real destination to drive toward. Set out now without blame — you've got the capacity matched to a worthy aim.",
    "Put your resources in service of something larger than yourself. The small, grasping person can't do this; they can't give away what abundance handed them.",
    "Stay within your measure and don't ape your neighbor's flashy display. No blame — the one who doesn't flaunt their wealth escapes the envy of those above.",
    "Your honesty wins people over and draws the same back; warmth balanced with real dignity carries the day. Sincerity worn without arrogance pulls everyone in.",
    "You're carried by something larger than yourself. When you hold real abundance and stay modest and grounded, support keeps flowing to you — nothing fails to further.",
  ],
  15: [
    "Modest and again modest — that humility carries you through the hard crossing and it goes well. Staying low and unassuming is exactly what gets you across the danger.",
    "Modesty that's earned enough to show, and everyone can see it's real. Hold to it and it goes well — humility that rings true wins people over.",
    "You do the heavy lifting and stay modest about it, and you carry the work all the way through. Good — real merit plus humility earns lasting loyalty.",
    "Keep showing humility in how you actually act. Move within your limits without overstepping — neither shrinking back nor pushing past the line.",
    "Without boasting about what you have, you draw people in; and now it's right to bring firm pressure to bear on what won't yield. Even hard measures, done humbly, are beyond reproach.",
    "Humility that's finally ready to act — now you can move decisively and set things right within your own domain. You've earned the standing to correct what's in your reach.",
  ],
  16: [
    "Loud, showy enthusiasm that's all display ends badly. Bragging about your connections and burning your excitement on vanity drains the source dry.",
    "Solid as rock, and not just for a day. Hold steady and it goes well — you flatter no one above, scorn no one below, and read the early signs before others see them.",
    "Enthusiasm that just gazes up at the powerful and waits brings regret; so does dithering. Stare at the people in charge instead of acting and you lose the moment by hesitating.",
    "You're the source the whole thing flows from, so big things are possible. Don't second-guess it — people gather around you the way a clasp draws loose strands together.",
    "Chronically held down, hemmed in by constant pressure from above — but not finished. The core in you isn't snuffed out; you persist.",
    "Enthusiasm gone blind, lost in itself — but if you snap out of it before it's too late and change course, no blame. Even self-delusion can be redeemed when you turn back in time.",
  ],
  17: [
    "Your old standard has shifted, and what anchored you now points elsewhere. Get out of your own bubble, meet new people, and the work will pay off.",
    "Chasing the easy, comfortable option means losing the one that actually matters. You can't have both — pick the one with real weight and let the trivial go.",
    "Commit to the serious work and you drop the shiny distraction. You get what you came for, but stay clear on your own aim so you're not pulled along.",
    "People start following you and your influence grows — which is exactly when others get suspicious. Stay honest and transparent about your motives and nothing sticks.",
    "You're genuinely committed to something good and you follow it without second-guessing. That kind of steadiness needs no justification.",
    "Your commitment is total, locked in all the way. Devotion this deep gets honored at the highest level — give yourself fully to what deserves it.",
  ],
  18: [
    "You're cleaning up a mess you inherited — a predecessor's bad code, a parent's debt, a broken system. It's tense work, but seeing it through restores the name and ends well.",
    "You're fixing damage left by someone you can't be harsh with. Go gently and don't force the correction; a heavy hand here only makes it worse.",
    "You're fixing the inherited problem a little too aggressively — minor regret for the overreach, but no real harm done.",
    "Tolerating the rot and making excuses for it lets the decay spread. Keep avoiding the cleanup and you'll be the one humiliated by it.",
    "You take up the cleanup the right way and people notice. Fixing what was broken earns you real recognition.",
    "You step back from the common grind to pursue your own higher work. Declining to play the usual game, you tend something that matters more — and that's worthy.",
  ],
  19: [
    "You move forward alongside others who share the goal, and the path is open. Hold firm to what's right and it goes well.",
    "You advance together toward something good and it works out. Move ahead without second-guessing it.",
    "Coasting in on charm and presumption gets you nowhere. But if you actually feel the mistake and fix it, the blame won't stick.",
    "You give yourself fully to the work or the person, no holding back, and it lands where it should. There's no error in total commitment.",
    "You lead wisely — through other people, not by grabbing every lever yourself. Delegating with judgment is what makes this work.",
    "You approach with generosity and a big, patient heart. Large-handed and unhurried, you can't go wrong here.",
  ],
  20: [
    "You're only skimming the surface and seeing the shallow view. Fine if little depends on you, but if you carry responsibility, that shallowness will cost you.",
    "You're looking at the whole thing through a keyhole, seeing one narrow slice. That limited view is fine for a small role, but embarrassing for someone who should see wider.",
    "Watch the actual results of your own choices — what advances, what backfires — and let that tell you when to move and when to hold. That's how you read the moment.",
    "Step back and take in the full landscape — the quality and reach of what's around you. See it clearly and you become someone worth bringing to the table.",
    "Look honestly at your own conduct and the effect you're having on others. Judge yourself by that mirror and you come out clean.",
    "Look at the whole picture, the lives and patterns beyond yourself, not just your own situation. See it that wide and you stand on solid ground.",
  ],
  21: [
    "A small fault gets you caught and corrected early, before it could grow. Better to be stopped now over something minor than let it compound — no shame in it.",
    "You come down hard and the wrongdoing is obvious, so you bite in deep. The rebuke is sharp, but given how plain the fault was, it's justified.",
    "You take on something rotten and it leaves a bad taste — you get a little burned by a problem that was tainted from the start. Mildly humiliating, but the task was genuinely hard, so it's not your fault.",
    "You hit something tough and tangled, but inside it you find what's solid and valuable. Stay sharp about the difficulty, keep upright, push through, and it pays off.",
    "You work through the dry, stubborn problem and find real gold in it. Keep your purpose, stay alert to the risk, and nothing comes back on you.",
    "You refused every warning and now you're clamped, unable to hear or move. Going deaf to correction is what brings the disaster down.",
  ],
  22: [
    "You'd rather walk on your own terms than ride in on something that isn't really yours. Turning down unearned comfort, you keep to your honest road.",
    "Your polish has to follow the substance underneath it, not lead. Style only works when it rises with the real thing it's decorating.",
    "Everything looks gleaming, fluent, effortlessly attractive. Enjoy it, but stay steady and grounded — keep it real over time and the good fortune lasts.",
    "Stripped of ornament, the plain truth arrives fast and clean. What looked like a threat turns out to be genuine; once you see clearly, the suspicion dissolves.",
    "Your offering is modest, almost embarrassingly small for the setting. There's a sting in giving so little, but sincerity over show wins out in the end.",
    "Strip the decoration back to plain white and nothing is left to fault. When form returns to simplicity, it has finally become true.",
  ],
  23: [
    "The rot starts at the base, where you can't see it — the legs of the bed are already going. Damage is undermining your foundation quietly; that's where the trouble begins.",
    "The decay climbs to the frame now, and the support that should hold is giving way. Standing alone here with no allies is dangerous — don't go it solo.",
    "You break from the people caught up in the decline, even though everyone around you is in it. Choosing what's right against the tide, you stay clean.",
    "The damage has reached the skin — it's hitting you directly now, no buffer left. The threat is right on top of you and there's no shelter.",
    "You line everyone up and lead them gracefully toward the light, and it all turns to your advantage. Bring people along in good order and nothing is wasted.",
    "One whole fruit is left uneaten, holding the seed of the next cycle — survive the stripping-away and renewal comes. The grounded carry on while the reckless tear their own house down.",
  ],
  24: [
    "You catch yourself before you've gone far down the wrong road and turn back. No need to beat yourself up — corrected early, the outcome is excellent.",
    "You return quietly and willingly, glad to come back in good company. Following what's good isn't weakness; it goes well.",
    "You keep relapsing — turning back, drifting off, turning back again — and it shows an unsettled mind. There's risk in all that wavering, but no lasting damage.",
    "Everyone around you is going one way, and you alone turn back toward what's right. Set apart from the crowd, your solitary return is the true one.",
    "You return with real, honest self-examination, weighing your own conduct. Searching yourself like that, you come home with nothing to regret.",
    "You missed the moment to turn back, and now it's too late — this brings serious, lasting harm. Push forward from here and it ends in total defeat you'll pay for a long time.",
  ],
  25: [
    "The genuine impulse is moving and it's clean. Act on it now, before you talk yourself out of it — the unguarded instinct knows the way.",
    "Do the work without tallying the payoff. Plow, ship, practice — and let results follow on their own timing instead of grading every step.",
    "Sometimes you get hit for nothing you did: the loss lands, the blame isn't yours. Take the cost cleanly and don't twist it into guilt.",
    "Hold what's genuinely yours and ask nobody's permission for it. Stay steady in your own lane and you can't really go wrong.",
    "This trouble isn't your doing, and it doesn't need fixing. Stop treating it, leave it alone, and it clears on its own.",
    "Forcing the right move at the wrong moment does damage. Even when you're clearly in the right, sit still — the timing forbids the step.",
  ],
  26: [
    "There's danger ahead, so stop. Don't push through it on principle — accept the brake and wait it out.",
    "The thing stalls on its own — the project loses its drive without your forcing it. No fault in standing down when the momentum quits.",
    "Now the path opens and you can run, but don't get loose. Keep your guard up daily, stay sharp, and it's good to have somewhere to go.",
    "Catch the problem before it hardens — set the limit while the young bull's horns are still soft. Curbing harm at the source is the big win.",
    "Tame the dangerous force at the root, not by fighting it head-on. Neutralize what makes it dangerous and it goes quiet — good fortune.",
    "The road finally opens wide. Everything you stored up and held back gets released at last, and it moves without resistance.",
  ],
  27: [
    "You let your own way of feeding yourself go slack to sit envying what someone else has. Chasing their full plate from a place of want is a bad move.",
    "You're scrounging for support from the wrong places — leaning on people below you, or begging the top for what your peers should give. Off-course, and it ends badly.",
    "Feeding yourself in a way that cuts against your own nature is hollow, however hard you cling to it. Drop it for a long while; nothing here pays off.",
    "Looking to those beneath you for support is fine here, and the hunger is sharp — a tiger's fixed stare. Want it intensely; you're still clear.",
    "Step off the usual path, stay put, and hold firm — that's the steady, fortunate move. Just know this isn't the moment for the big crossing.",
    "You're the source others draw their nourishment from. Carry the weight, respect the risk that comes with it, and it's good — now you can make the great crossing.",
  ],
  28: [
    "The load is heavy, so be meticulous at the start — lay the groundwork as carefully as white rushes under an offering. That much care early keeps you clean.",
    "Against all odds, the dead branch buds and the old pairs with the young: something written off comes back to life. Take it; it's favorable.",
    "You're carrying more than the structure can hold and it's bending to the breaking point. Going it alone and stubborn here ends badly — get support or lighten the load.",
    "Brace the overstrained thing and it holds firm — good. But if you're propping it up for some hidden agenda of your own, that's where the shame comes in.",
    "A late, surface revival — the old branch flowers, the mismatched pairing happens. No real harm, but no lasting credit either; the bloom can't hold.",
    "You wade in over your head and go under. It costs you, but you're not to blame — you took the loss doing the right thing.",
  ],
  29: [
    "You've fallen into danger inside danger, the deepest pit. This is the bottom, and it's bad — you've lost the way entirely.",
    "Surrounded by danger on every side, don't try for the dramatic escape. Aim for one small, certain gain and take a single sure step.",
    "Everywhere you turn it's danger ahead and danger behind. Don't move — any action here just sinks you deeper.",
    "Strip it to essentials — a jug of wine, a bowl of rice passed plainly through the window. Honest, no-frills sincerity gets you through clean.",
    "Don't overfill the hole — just bring it level to the brim and stop there. Do enough to clear the danger and no more, and there's no fault.",
    "Tied up and stuck in the thorns, shut away for years with no way out. This is being deeply, lastingly trapped — misfortune.",
  ],
  30: [
    "The day starts scattered and your steps are crisscrossed and confused. Move with care and respect through the early mess and you stay clear.",
    "You're lit from the balanced center, steady and bright. This is the rare clean radiance — supreme good fortune.",
    "It's the light of the setting sun. Either make peace and sing or fall apart over what's ending; clinging to what has to fade is the misfortune.",
    "It comes on too sudden — a flare-up that blazes and dies and gets thrown out as fast as it caught. Fire with no discipline can't last.",
    "The tears pour and the grief breaks open, but the burning-through cleanses you. Out the far side of real sorrow, good fortune follows.",
    "Strike decisively but precisely: take out the ringleaders, spare the ones who just got swept along. Targeted force, not a massacre — and you stay clean.",
  ],
  31: [
    "The pull barely registers — a twitch in the toe, all internal. The interest is real but far too faint to actually move anything yet.",
    "The pull is reaching you and the urge is to bolt forward — don't. Rushing it ends badly; holding still and waiting is the good move.",
    "You're moving only because you're following the crowd, like thighs that go wherever the body goes. Tagging along and clinging to others gets humiliating.",
    "Stay the course and it pays — the regret clears. But if your heart keeps flip-flopping in restless agitation, only a few will follow your wandering aim.",
    "The connection is stuck up at the stiff back of the neck, never reaching the heart. It's shallow and won't move much — but at least nothing here goes wrong.",
    "It's all in the jaw — cheeks, tongue, pure talk and persuasion. Just words, with no real movement underneath them.",
  ],
  32: [
    "You're forcing permanence on day one, demanding the long-term result before the thing has had any time. Pushing this hard now ends badly and gains nothing.",
    "Hold to the steady center and the regret dissolves. Your strength is matched to the moment — keep doing exactly this.",
    "Without a steady home for your principles, you'll keep getting embarrassed. Flip-flopping isn't freedom; cling to that inconstancy and it only brings shame.",
    "You've been grinding in a field with no game in it — steady effort aimed at the wrong place. Persistence on a dead lead yields nothing; move it.",
    "Steadfastly following one fixed course suits the one whose role is to follow, but fails the one who has to weigh each case fresh. Match the rule to your role.",
    "Endurance that's all churn and never settles isn't endurance. Constantly stirred and never at rest, this ends badly — what can't rest can't last.",
  ],
  33: [
    "You waited too long to step back, and now you're exposed. Don't push forward; sit still and start nothing.",
    "Hold your position with quiet, unbreakable resolve. Nothing and no one can pull you off it.",
    "You can't pull back cleanly because too much is tied to you. Workable for small things, but no way to run anything that matters.",
    "The strength here is letting go cleanly. Walk away without clinging, while the weaker version of you keeps grasping.",
    "Leave while things are still warm. Exit before it sours, and you leave nothing burnt behind.",
    "You're out, you're clear, and you're light about it. No second-guessing, and the way ahead is wide open.",
  ],
  34: [
    "You're eager to charge, but you don't have the means yet. Moving now backfires.",
    "Strength that keeps its measure, neither forcing ahead nor falling back. Stay steady and you win.",
    "Don't bull through it. Force for its own sake gets you stuck, tangled in your own momentum.",
    "The block clears and you move with huge force but no strain. Keep your discipline and the regret fades.",
    "Let go of the thing you've been gripping too hard. Ease your hold and it releases without harm.",
    "You're jammed by your own push, stuck either way. See the bind clearly, bear with it, and it resolves in time.",
  ],
  35: [
    "You advance and get rebuffed. Stay steady, don't force the trust that isn't given yet, and you're fine.",
    "A slow, disheartening climb. Hold your course anyway, and recognition comes from the one above you.",
    "Everyone moves forward together in trust. With the group aligned, the path opens without friction.",
    "Climbing by greedy, furtive grabbing. However well it seems to go, that way is dangerous.",
    "Stop tracking your wins and losses. Move forward openly and it works out.",
    "Turn the force inward and fix your own house first. Harsh but right; just don't lean on it too long.",
  ],
  36: [
    "Early in a dark stretch you take a hit and go hungry. Keep moving toward your aim despite the criticism.",
    "You're wounded but not crippled. Act fast to get yourself clear, and the escape holds.",
    "You can strike at the real source of the trouble, but don't expect to set everything right at once.",
    "You get close enough to see how rotten it truly is. Then you quietly walk out.",
    "Trapped near the darkness, hide your brilliance but keep your resolve intact. Persistence carries you.",
    "The one casting the shadow rose high, then crashed. Darkness this complete consumes itself in the end.",
  ],
  37: [
    "Set clear rules early, before bad habits take root. Structure up front keeps the whole thing healthy.",
    "Don't chase your own impulses. Do the steady, unglamorous work that keeps everything fed and running.",
    "Running hot with standards still beats letting it all slide into joking around. Some friction now saves the whole.",
    "Whoever steadily enriches the group is its real asset. Great fortune comes from that quiet care.",
    "Lead by trust, not by fear. When people aren't anxious around you, everyone is at ease.",
    "Sincerity carried all the way through earns lasting respect. Consistency is what finally makes them believe you.",
  ],
  38: [
    "Don't chase what walked off; it comes back on its own. And when you cross bad actors, just stay careful.",
    "An unplanned, informal encounter mends the rift. No fault in seizing a chance meeting when both want to reconnect.",
    "Everything's blocked and it feels humiliating at first. Rough start, but it comes right in the end.",
    "Cut off and alone, you find one true ally. Risky still, but joining in good faith clears the blame.",
    "The barrier between you and your ally is breaking down. Go meet them; it's no mistake.",
    "You misread an ally as an enemy. Drop the suspicion, see they're on your side, and the tension finally breaks.",
  ],
  39: [
    "Pressing into the block gets you stuck. Choosing to wait and turn back now is what earns respect.",
    "You hit wall after wall, but it's for the duty, not for you. Don't falter; keep at it.",
    "Don't advance into the block. Come back, and the people relying on you are glad you returned.",
    "Instead of forcing ahead alone, pull back and gather the people who'll share the hard road.",
    "At the deepest point of the difficulty, holding firm at the center, the help arrives.",
    "Don't push out; come back to lend your strength where it's needed, and seek wise counsel. That achieves a lot.",
  ],
  40: [
    "The tension just broke. Rest, do nothing more; nothing else needs to be said.",
    "Clear out the cunning and deceit around you, and hold a straight course. That's what wins.",
    "Flaunting a position you haven't earned invites trouble. The mismatched display brings humiliation.",
    "Let go of the low, unworthy attachment. Only then do the people worth trusting come near.",
    "Once you genuinely cut loose, the small-minded fall away on their own. Release is the whole point.",
    "Take out the entrenched obstacle with one well-prepared, decisive strike. Nothing left to hold you back.",
  ],
  41: [
    "Helping someone is fine, even worth dropping your own work for — but check the cost first. Give freely, not past the point that drains you.",
    "The way to give the most is to give without depleting yourself. Hold your position; don't overextend, or you lose the very thing they need.",
    "Three is a crowd here — one has to go. Pair down to the real partnership; the right configuration finds itself once you stop forcing the third.",
    "Cut the thing that's been weighing you down, and people show up glad to help. Shed the baggage and watch the support arrive.",
    "An offer or windfall lands that nobody can argue with — every sign points the same way. This is the rare, clean yes.",
    "You lift others without costing them anything, and help comes from everywhere. Real generosity isn't subtraction; the old boundaries stop mattering.",
  ],
  42: [
    "Now is the moment for the big move — backing is flowing to you from above, so swing hard. Bold action here pays off cleanly.",
    "Increase arrives that can't be reversed, confirmed from every angle. Stay steady and committed; even your modest efforts get blessed.",
    "Growth comes through a setback, oddly enough — a hard event that ends up helping. Stay honest, walk the center, report plainly, and you take no blame.",
    "Hold the middle line and your advice gets heard at the top. You've earned enough trust to move people and shift how things are run.",
    "Lead with genuine goodwill and ask for nothing back. The kindness itself is what gets recognized — that's the whole return.",
    "You take and give nothing; now people turn on you. An unsteady, self-serving heart is what brought the trouble down.",
  ],
  43: [
    "Eager to charge ahead on raw confidence, but if you can't actually win, the push becomes the fault. Don't advance on strength you don't have.",
    "Stay alert and sound the alarm even at night. You don't have to be afraid — you saw it coming and you're prepared.",
    "Showing your resolve too openly on your face invites trouble. Walk your path alone through the mess, take the dirt and the resentment, and you still come out clean.",
    "You're stuck and stumbling, and being led would fix it — but you won't take the help. The advice is right there; you just don't believe it.",
    "Root out the lingering problem decisively, like pulling weeds. Hold the middle and don't go to extremes, and there's no blame.",
    "You stop short of finishing and skip the last warning — and that's where it goes wrong. The final scrap of the problem is exactly what you can't ignore.",
  ],
  44: [
    "Catch it now, at the very start, with a hard stop. Restrain it early and you're fine; let it run and a small thing thrashes out of control.",
    "You've contained the problem quietly — fine for now. But don't try to pass it off onto others or make it shared; keep it held where it is.",
    "You're stuck and the going is rough, with no good footing. Stay aware of the danger and you avoid a serious mistake.",
    "You've lost touch with the people below you, and now there's nothing there. That broken connection is what brings the trouble.",
    "Keep your real strength hidden and unforced, like fruit under leaves. Don't grasp; what's meant for you arrives on its own.",
    "You meet everyone stiff, horns out, holding yourself above. No one's really to blame but you — it's just an isolating, embarrassing way to be.",
  ],
  45: [
    "Your commitment is wobbling and the group is scattering. Speak up — one honest reach of the hand turns the mess into relief. Move forward unafraid.",
    "Let yourself be pulled into the group instead of resisting. A small, sincere gesture is all it takes to belong.",
    "You want in but keep getting left out, sighing on the edges. Go ahead and join anyway — a little awkwardness, but no real harm.",
    "Great outcomes come when you gather people for the shared good, not to build your own following. Drop the self-interest and it works.",
    "Holding a leadership spot is fine, but if trust isn't there yet, only steady, long-term consistency dissolves the doubt. Earn it over time.",
    "You're grieving being shut out, even in tears. Stay with it — those who genuinely ache to be included eventually find their way in.",
  ],
  46: [
    "You're rising with real support and being welcomed up. The ground is willing — this is a great start to the climb.",
    "You don't have much to offer, but offered with sincerity it's accepted. Show up honest and small; that's enough right now.",
    "The path ahead is wide open, an empty city, no resistance. Advance freely — nothing is blocking you.",
    "Your ascent gets recognized and consecrated by those above. The rise is legitimate now — good fortune, no blame.",
    "Keep climbing one deliberate step at a time. Steady persistence up the stairs is what brings the good outcome — don't rush it.",
    "Climbing blindly in the dark, just to keep climbing. The only thing that saves it now is unceasing, watchful care so you don't lose the way.",
  ],
  47: [
    "Worn down and isolated, stuck in a dark place with no one in sight for a long stretch. This is depletion at its lowest — wait it out.",
    "Drained even while surrounded by comfort, but relief and recognition are on the way. Make the offering, stay put; pushing out now backfires, though you're not at fault.",
    "You back yourself into stone and grab at thorns, then come home to find your support gone too. Forcing it here only makes it worse.",
    "Help comes, but slowly and awkwardly — stuck in borrowed comfort. It's humiliating, but the matter does reach its end.",
    "Cut down and constrained even by those who should help, relief comes only gradually. Don't force it; the quiet, patient offering is what works.",
    "Tangled up and teetering at the edge, exhausted. The turn comes the moment you admit the old moves bring regret — own that, change, and going forward pays off.",
  ],
  48: [
    "You're a stagnant, neglected source — nothing fresh, no one drawing from you. When you stop renewing yourself, people stop coming.",
    "You aim small, chasing minnows, and your one tool is cracked and leaking. Effort drains away because the means are broken — fix the basics.",
    "You've done the cleanup and the value is real, but no one's drawing on it — a waste that stings. The work is sound; what's missing is someone with the clarity to use it.",
    "You're shoring up the foundation, lining the well with stone. Not glamorous, but no blame — repairing the source is time well spent.",
    "The source is clear, cold, and ready — fully usable. Everything's in place to draw on now.",
    "Drawn from freely and never sealed off — the source stays open to all. This is the whole point: dependable, generous, and that's where the real good fortune is.",
  ],
  49: [
    "The case for change is real but the moment isn't. You're tied down for a reason — hold, don't launch anything yet.",
    "The right day has finally arrived. Make the change now: move forward and you're clear, with nothing to regret.",
    "Forcing the change blows up; sitting on it is also dangerous. Once the idea has cycled around enough to earn trust, then act on it.",
    "People believe in it now, so the doubt is gone. Overturn the old way at this moment and it goes well.",
    "You change so cleanly and visibly that no one needs convincing — the new direction is obvious and people trust it on sight.",
    "You refine the new order into something polished; others just rebrand the surface. Don't push for more now — settle in and hold the line you've won.",
  ],
  50: [
    "Tip out the old residue before you refill. What looks like discarding something improper is just clearing stale buildup so the real work can start.",
    "Your vessel is full and the work is solid. Rivals envy you but can't touch you — stay focused and it goes well.",
    "Your value goes unused because the connection is broken and no one can carry the work. Repair the link, and once it clears, it ends well.",
    "You took on more than you could hold and it spilled — the trust placed in you is wasted. That's the shame of being unequal to the task.",
    "You've got the right people and solid means to carry the work. Stay disciplined and correct, and it holds.",
    "Everything is in place — strong, refined, dependable. This is the high point where nothing works against you; proceed.",
  ],
  51: [
    "The shock hits and you panic, then it passes into relief and even laughter. Good — the scare sharpened your caution instead of breaking you.",
    "A jolt hits and you think you've lost something valuable, so you retreat to safety. Don't chase it; what's gone comes back on its own in time.",
    "The disruption leaves you rattled and off-balance. If the alarm gets you moving in the right direction, no harm comes of it.",
    "The shock lands and you're stuck — sunk in inertia, unable to respond while you stay bogged down.",
    "Disruptions keep coming from every side, but nothing real is lost. Stay on the work that can't be dropped.",
    "The blow brings chaos and you're frozen — pushing forward now backfires. It's hit someone near you, not you yet, so there's no shame in holding back, even if others grumble.",
  ],
  52: [
    "Stop before you've taken the first step. No harm in not starting — just keep that restraint steady.",
    "You hold back, but you're pulled along by something bigger that you can't stop, and it leaves you uneasy and resentful.",
    "Forcing yourself to stop by clamping down rigidly only strains and grinds — that kind of white-knuckle restraint eats at you.",
    "You bring yourself to rest and steady the body. No harm, though the calm hasn't reached all the way through you yet.",
    "Hold back your words so they come out measured and in order. The regret disappears.",
    "Stillness that comes from genuine completion, not strain. This is the settled quiet of being done, and it goes well.",
  ],
  53: [
    "You're just arriving and you're exposed — junior, criticized, on shaky footing. There's risk and talk, but no real fault in it.",
    "You've reached safer ground and can rest, eat, and settle into the work with ease. This goes well.",
    "You overreach past your safe range: you charge out and don't come back, or you start something that won't bear fruit. It goes badly — focus on defending what you have.",
    "You land in a spot that isn't really yours, but you take it patiently as a place to rest for now. No harm in accepting it.",
    "You're near the top, and for a long stretch nothing seems to come of it. But in the end nothing can block the outcome — it works out at last.",
    "You reach the heights, and even what you shed becomes useful to others. It goes well; the long climb arrives somewhere that means something.",
  ],
  54: [
    "You come in from a lesser position with limited room to act. Work within those limits and serve where you can, and it still goes well.",
    "You can only half-see the situation, and you're being slighted. Hold steady and keep faith even from this overlooked, dim spot.",
    "You wanted the better arrangement but had to wait in a lesser role, and only by accepting the humbler place do you find a way forward. The proud waiting was never going to hold.",
    "You let the moment pass on purpose; the right opportunity will come in its own time. Better to wait for the right one than grab the wrong one now.",
    "Real worth doesn't need display — your substance outshines anyone's showier presentation. Like the moon just before full, this is about as good as it gets.",
    "All the forms are observed but there's nothing inside — empty basket, bloodless ritual. Going through the motions with no substance gets you nowhere.",
  ],
  55: [
    "You meet a true peer, an equal in caliber. Even intense, concentrated time together is no mistake — go forward with them and it earns recognition.",
    "Things have gotten so murky that you can't see clearly even at the obvious moment; pushing now just breeds suspicion. Let your honesty show through instead, and it turns out well.",
    "The obstruction is so thick you can barely make out anything, and your means to act are broken. No fault — you're genuinely unable right now, not unwilling.",
    "You've been in the dark, but now you meet someone of your own kind who clears it. The encounter is what turns it around.",
    "Capable people step forward and bring you backing and praise. It goes well.",
    "You let grandeur wall you off until your own house is empty and no one's been around for ages. That's the failure — scale that hollows out the life inside it.",
  ],
  56: [
    "You're out of your element, so fussing over petty details and trifles is exactly how you bring trouble on yourself. Don't sweat the small stuff here.",
    "On unfamiliar ground, you keep your resources close and earn the loyalty of a few reliable people. That's how you get steady footing in a strange place.",
    "You torch your own shelter and lose the people who were helping you. Pushing on now is just dangerous — you wrecked your own base through carelessness.",
    "You find a place to rest and get some security and means to protect yourself, but it doesn't sit right. The safety is uneasy because it isn't really yours.",
    "You take your shot and even though it costs you something, the skill you show wins you recognition and standing. Talent shown well earns favor even far from home.",
    "You get comfortable and laugh, then it burns down and you're left grieving — you lose what mattered by getting careless. When you're the outsider, forgetting to stay humble is what ruins you.",
  ],
  57: [
    "You keep stepping forward and pulling back, unsure. Stop wavering — set a firm intention and let discipline, not mood, steady the decision.",
    "There's something hidden under the surface here. Don't go it alone: bring in people who can see what you can't, and ask plainly.",
    "Saying the same thing over and over stops being persistence and turns into nagging. Make the point once or twice, then trust it to land.",
    "The doubt clears. Your patient, steady pursuit finally pays off in full — you bring back more than you expected from the long effort.",
    "Hold the course and the worry fades. The start was messy, but there's a real finish here; plan carefully before and after the move, and it works out.",
    "You're digging at the same problem again, but now you've spent your tools and your leverage. Forcing it further only costs you — walk away.",
  ],
  58: [
    "Quiet, settled contentment with no craving for more. You're at peace with yourself, and that calm is exactly where things go right.",
    "Real gladness coming from inside, not from anyone's approval. Trust it — it dissolves the second-guessing and points you straight.",
    "Chasing pleasure from outside, working to be entertained and flattered, leads nowhere good. Stop courting it; it won't fill you.",
    "You're torn between two pleasures and can't rest. Draw a clear line, cut off the one that's harming you, and the relief is immediate.",
    "Leaning on something that quietly drains you is a real danger. Guard your firmness against the comfort that's actually dissolving it.",
    "Charm that exists only to lure and seduce, all surface and no truth, never lands anywhere solid. Don't be the act, and don't fall for it.",
  ],
  59: [
    "Address the rift while it's still small, and do it fast and hard. Catch the misunderstanding or crack before it sets, and you're fine.",
    "When things start coming apart, move quickly to whatever steadies you. Find your footing, your refuge, and the regret clears.",
    "Dissolve your own ego and petty concerns. Turn outward, stop guarding your small self, and there's nothing here to regret.",
    "Break up your own clique and the loyalty to your narrow circle. Out of that scattering comes a far bigger alliance you couldn't have planned.",
    "Broadcast the message widely and spend down what you've hoarded for the shared good. In a time of breakdown, lead steadily and you stay clean.",
    "Get yourself clear of real harm — disperse the danger before blood is shed and put distance between you and it. Avoiding the wound is no fault.",
  ],
  60: [
    "You don't have to cross every line or chase every opening. Knowing when to stay put and do nothing is its own discipline — hold still.",
    "You held back when it was time to move. Restraint past its moment isn't caution, it's paralysis, and here it costs you the opening.",
    "Refuse all limits and the spending and excess catch up with you in regret. Don't look for someone to blame — this one's on you.",
    "Limits you can carry easily, without strain or resentment. When the discipline feels natural rather than forced, it carries you to success.",
    "Restraint you actually embrace, even enjoy, wins you respect. Keep operating with this kind of graceful self-discipline and it earns honor.",
    "Harsh, joyless, self-punishing limits aren't sustainable. Grind on this way and it backfires — ease up, and the regret eventually passes.",
  ],
  61: [
    "Get genuinely settled and prepared within and things go well. But if you're secretly angling at someone, your own heart won't let you rest.",
    "Real sincerity resonates even when no one's watching. Speak honestly to the right person and you'll be answered in kind — no performance needed.",
    "Tying your whole mood to someone else leaves you swinging between elation and grief. Anchor yourself, or every drum and silence will toss you.",
    "Time to leave your lesser companions and rise toward the higher path, even if it means going on alone. Cutting those ties is no fault.",
    "Sincerity so solid it binds people together like a cord. Your integrity holds the whole thing in place — keep it firm and there's no blame.",
    "All crow and no substance, straining to sound impressive with nothing behind it. Hollow noise can't last; keep faking it and it ends badly.",
  ],
  62: [
    "Reaching far past your strength right out of the gate. Overreach this early, before you've built anything, and you fall — start small.",
    "Aim slightly lower than your grand target and you'll connect with what's actually within reach. Stay modest and in proportion, and you're fine.",
    "Drop your guard now and you'll get hit from behind. This is a moment for extra caution, not confidence — watch your back.",
    "No blame, but don't force your way through. Pushing on is dangerous; hold firm, sit tight, and keep your restraint instead of acting.",
    "Heavy clouds, still no rain — the conditions aren't there to deliver. Accept that small means can't finish a big job; take the modest, reachable win.",
    "Going further and further past the mark, flying away from any landing. This is ruin you bring on yourself — pull back before you can't.",
  ],
  63: [
    "The work's done and you're tempted to charge ahead. Hit the brakes at the crossing instead; holding back right now keeps you out of trouble.",
    "You've lost something you relied on. Don't chase it — let it go, stay your course, and it comes back to you on its own before long.",
    "This is a long, grinding campaign that takes years to win. Take it on only with the depth and stamina it demands — it's not a casual move.",
    "Even your best, most finished work has leaks starting to show. Stay alert all day — the seams are quietly loosening, so patch as you go.",
    "A modest, sincere effort beats a lavish, hollow one. Don't out-spend the rival — out-mean them; genuine intent outweighs the bigger show.",
    "Pressing on past the finish drowns you. The danger now is treating the summit as a place to relax and keep climbing — stop at done.",
  ],
  64: [
    "You're not strong enough yet and pushing across now just gets you stuck and embarrassed. Wait until you've actually gathered the force.",
    "Pump the brakes and hold back for now. Sticking with that restraint, instead of lunging at the unfinished thing, is exactly right.",
    "Launching right now, before the moment's ripe, goes badly. But once conditions line up, this is precisely when to make the big crossing.",
    "Stay the course and the regret clears. This is a hard, multi-year push that takes real force — see it through and the rewards do come.",
    "Hold firm and it goes well, no regrets. Your clarity is genuine, and leading with that kind of true, sincere light is what makes it work.",
    "Almost there, you can ease up and celebrate a little — that's fine. But lose your head in the excess and you throw away the discipline that got you here.",
  ],
};
